### ISSUE TITLE
Would save settings on Linux cmdline termination signal

### ISSUE THREAD

**Issue by bugith** [corrados/jamulus#70] opened 2020-04-15 08:14 UTC
For scripting integration with qjackctl it would be nice if pkill jamulus (which defaults to send SIGTERM) would save current settings as from GUI Ctrl+Q|View/Exit.
Same issue example for LibreOffice : https://ask.libreoffice.org/en/question/159189/close-libreoffice-gracefuly-from-command-line/

**Comment by corrados** [comment] 2020-05-19 18:55
@pljones This Issue should be solved by your SIGTERM code I recently merged, right?

**Comment by pljones** [comment] 2020-05-19 20:28
I'd have expected it - the server should terminate as if the window closed.  The client won't have changed behaviour.

**Comment by corrados** [comment] 2020-05-20 16:36
I just tested it on Linux. I opened the server GUI and changed a setting. Then I killed the server in the shell by pressing Ctrl+c. Then I reopened the server GUI and the changed setting was successfully stored and recovered. So the requested functionality is implemented and works -> closed.

**Comment by corrados** [comment] 2020-05-20 16:38
Ups... It is not about the server but the client. I just tested it with the client and it does not work. If I kill the client GUI, the settings are not stored.
@pljones Why is the storing of settings on Ctrl+c only implemented for the server GUI? Is it done on purpose?

**Comment by pljones** [comment] 2020-05-20 16:49
Because I only added it to the server for terminating jam recordings.  That it tidied up the server closing was a by-product, more or less.  The signal handler went into server.cpp so that the server could terminate normally, moving some of the code from the dialog into server.cpp, too.

Similar changes would be needed to client.cpp to add the handling and to wherever the existing window closure intercept that saves the settings.

**Comment by corrados** [comment] 2020-05-20 17:11
I just checked in the code. It is no big deal to implement that for the client, too. Do you want to do it?

**Closed** 2020-05-21 19:27 UTC
Labels: feature request

**Comment by corrados** [comment] 2020-05-21 19:48
I just confirmed that the solution implemented by pljones works as expected: https://github.com/corrados/jamulus/pull/259
