### ISSUE TITLE
Command-Q quits client but it is still listed in the client list in Jamulus Server window

### ISSUE THREAD

**Issue by Skeezixes** [corrados/jamulus#268] opened 2020-05-23 02:03 UTC
Under MacOS 10.15.4, server and client running on the same machine, if the client is connected to the server and I quit the client with Command-Q, the Jamulus client windows close and the client seems to be dead. 

But in the Jamulus Server window this client is still listed in the client list.

When I restart the Jamulus client (from the icon in the Dock), I see the Connect (rather than the Disconnect) button, no active level meters, etc., so the client appears to have actually been disconnected.

**Comment by corrados** [comment] 2020-05-23 06:41
I cannot reproduce your issue. I just tried it out on my Mac. I started the Jamulus server and then the Jamulus client and connected with the client to the local server. When I now press Command-Q, the client quits and in the list of the Jamulus server GUI I immediately cannot see the connection anymore. So the client correctly shut down and disconnected from the server.
Recently we made some changes to the signal handling. Maybe that fixed the issue. I'll do a new Jamulus release this weekend. If that is out, can you please try again on your Mac if the issue is still there?

**Comment by Skeezixes** [comment] 2020-05-23 07:00
Will do. Unfortunately I couldn’t replicate it myself later tonight. I will see if I can figure out if/when it happens with the new release.

**Comment by corrados** [comment] 2020-06-01 20:40
Any updates on this? Could you reproduce the issue?

**Comment by corrados** [comment] 2020-06-11 20:40
I assume that you could not reproduce the issue. So I will close this issue now. If you still see this issue, just re-open this Issue again.

**Closed by corrados** 2020-06-11 20:40 UTC
Labels: bug
