### ISSUE TITLE
Strange behaviour with GUI and OSX

### ISSUE THREAD

**Issue by remixmabix** [corrados/jamulus#23] opened 2020-03-28 15:54 UTC
Hello, after compiling Jamulus with Jack Audio Toolkit Support everythin is fine but i got one exception :

I start the .app normally and everything is fine until after a while when the window is not focused but is running in background (UserInteractiveNonFocal),

I got a lot of : 

	JackEngine::XRun: client = Jamulus was not finished, state = Triggered
	JackAudioDriver::ProcessGraphAsyncMaster: Process error

I precise that when I focus on the Jamulus window again, the Xruns disappear.

Then I noticed this kind of message in OSXConsole.

	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checkAgainstApp is : Jamulus
	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] | entered. checking app: Jamulus
	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Adding to relaunchArray: Jamulus

	runningboardd	Acquiring assertion targeting executable<Jamulus(1078646027)> from originator [daemon<com.apple.coreservices.launchservicesd>:202] with description <RBSAssertionDescriptor; frontmost:10277; ID: 347-202-616; target: 10277> attributes = {
	    <RBSDomainAttribute: 0x7fcaf3710f90; domain: com.apple.launchservicesd; name: RoleUserInteractiveFocal; sourceEnvironment: 0x0>;
	}
	runningboardd	Assertion 347-202-616 (target:executable<Jamulus(1078646027)>) will be created as active

	runningboardd	Finished acquiring assertion 347-202-616 (target:executable<Jamulus(1078646027)>)

	runningboardd	[executable<Jamulus(1078646027)>:10277] Ignoring jetsam update because this process is not memory-managed
	runningboardd	[executable<Jamulus(1078646027)>:10277] Set darwin role to: UserInteractiveNonFocal
	runningboardd	[executable<Jamulus(1078646027)>:10277] Ignoring GPU update because this process is not GPU managed

	Jamulus	LSExceptions shared instance invalidated for timeout.

Problem occurs generally with this error message before.

	par défaut	16:24:58.539627+0100	Activity Monitor	(reg) gpu 0x3177 flags 0x10 (IG) vid.did=8086.5927 b:d:f=0:2:0 
	gpu 0x3177        pci 0x10000020c IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/IGPU@2
	gpu 0x3177       agdc 0x1000006eb     /AppleIntelFramebufferController/IntelFBClientControl
	gpu 0x3177       gpuc 0x000000000 
	gpu 0x3177 agdpclient 0x1000006f5     /AppleIntelFramebufferController/IntelFBClientControl/AppleGraphicsDevicePolicy/AGDPClientControl
	gpu 0x3177      accel 0x1000004aa     /IntelAccelerator
	gpu 0x3177      fb0:0 0x1000004ac     /AppleIntelFramebuffer@0
	gpu 0x3177      fb1:1 0x1000004ad     /AppleIntelFramebuffer@1
	gpu 0x3177      fb2:2 0x1000004af     /AppleIntelFramebuffer@2

Also I noticed that without the GUI this problem does'nt occur.
It could be a workaround to start on cli only but I need to mute myself before entering the server as I did'nt see any of these parameters in the ini file.

Thanks.

OSX 10.15.4
QMake version 3.1
Using Qt version 5.14.1
jackdmp 1.9.13

**Comment by corrados** [comment] 2020-04-05 18:20
Unfortunately my Mac is too old to run OSX 10.15. So I cannot reproduce this on my Mac.

**Comment by remixmabix** [comment] 2020-04-05 23:41
Hello again i try to help as best as I can, After doing a dtrace :

I can first see this :

	sendto(0x3, 0x600001FC7600, 0xBC)    = 188 0
	recvfrom(0x3, 0x7FE135054A00, 0x4E20)    = 188 0
	sem_wait(0x10, 0x0, 0x0)     = 0 0

Then after a little time two lines are added sometimes :
	
	>>>> sendto(0x3, 0x6000028FCFB0, 0xD)     = 13 0
	recvfrom(0x3, 0x7FE135054A00, 0x4E20)    = 188 0
	>>>> recvfrom(0x3, 0x7FE135054A00, 0x4E20)    = 13 0
	sem_wait(0x10, 0x0, 0x0)     = 0 0

Then this appeared twice a couple of times :

	recvfrom(0x3, 0x7FE135054A00, 0x4E20)    = 188 0
	recvfrom(0x3, 0x7FE135054A00, 0x4E20)    = 188 0

Then I had this message :

	recvfrom(0x3, 0x7FE135054A00, 0x4E20)    = 188 0
	recvfrom(0x3, 0x7FE135054A00, 0x4E20)    = 188 0
	recvfrom(0x3, 0x7FE135054A00, 0x4E20)    = 188 0
	recvfrom(0x3, 0x7FE135054A00, 0x4E20)    = 188 0
	recvfrom(0x3, 0x7FE135054A00, 0x4E20)    = 188 0
	recvfrom(0x3, 0x7FE135054A00, 0x4E20)    = 188 0
	recvfrom(0x3, 0x7FE135054A00, 0x4E20)    = 188 0
	recvfrom(0x3, 0x7FE135054A00, 0x4E20)    = 188 0
	recvfrom(0x3, 0x7FE135054A00, 0x4E20)    = 188 0
	recvfrom(0x3, 0x7FE135054A00, 0x4E20)    = 188 0
	recvfrom(0x3, 0x7FE135054A00, 0x4E20)    = 188 0
	recvfrom(0x3, 0x7FE135054A00, 0x4E20)    = 188 0

And after this not long after (I think that this is where the error messages are prompted in Jack and started audio degradation) :

	bsdthread_ctl(0x100, 0x0, 0xDA1F)    = 0 0
	bsdthread_ctl(0x100, 0x0, 0xDA1F)    = 0 0
	bsdthread_ctl(0x100, 0x0, 0x0)     = 0 0
	bsdthread_ctl(0x100, 0x0, 0x0)     = 0 0
	bsdthread_ctl(0x100, 0x0, 0xDA1F)    = 0 0
	kevent_id(0x60000048AE00, 0x7FFEEB24F010, 0x1)     = 0 0
	workq_kernreturn(0x40, 0x70000A7A9B80, 0x0)    = 0 -2
	bsdthread_ctl(0x100, 0x0, 0x0)     = 0 0
	bsdthread_ctl(0x100, 0x0, 0xDA1F)    = 0 0
	bsdthread_ctl(0x100, 0x0, 0xDA1F)    = 0 0
	bsdthread_ctl(0x100, 0x0, 0x0)     = 0 0

....
	kevent_id(0x60000048AE00, 0x7FFEEB24F010, 0x1)     = 0 0
	workq_kernreturn...
....
	psynch_mutexdrop(0x6000016D8810, 0x2F00, 0x2F00)     = 0 0
	psynch_mutexwait(0x6000016D8810, 0x2F02, 0x2E00)     = 12035 0
....
	dtrace: error on enabled probe ID 2186 (ID 165: syscall::read:return): invalid kernel access in action #12 at DIF offset 68
....
	kevent_id....
....
	getentropy(0x7FFEEB240880, 0x20, 0x0)    = 0 0
	getentropy(0x7FFEEB2408E0, 0x40, 0x0)    = 0 0
....
	madvise(0x1114E3000, 0x9000, 0x9)    = 0 0
	madvise(0x1114E3000, 0x9000, 0x9)    = 0 0
....
	sigprocmask(0x1, 0x0, 0x7FFEEB24B7E0)    = 0x0 0
	sigaltstack(0x0, 0x7FFEEB24B7D0, 0x0)    = 0 0
....


I read something about SIP but maybe you are more aware than me.
Thanks for your help

**Comment by corrados** [comment] 2020-04-08 20:42
Puh... I am no Mac expert. Thank you for the logs but they do not say anything to me. The only way to solve this problem would be to have it reproduced at my Mac. Unfortunately my Mac is too old for the newest OS, sorry...

**Comment by Snayler** [comment] 2020-04-21 11:43
Volker, if you have a powerful enough machine, it's possible to install MacOS as a virtual machine, for debugging purposes. I use that approach while developing cross platform apps, so that I can have a way to test them without having to actually purchase the hardware, and it works wonders.

**Comment by corrados** [comment] 2020-04-21 13:51
Unfortunately not. I have a HP EliteBook 2540p.

**Comment by corrados** [comment] 2020-05-13 14:50
Maybe this is related: https://sourceforge.net/p/llcon/discussion/server/thread/154ade8a00

**Comment by AronVietti** [comment] 2020-05-20 03:34
I was able to reproduce this pretty quickly. @corrados Going to take a crack at this, if you want to assign it to me, firing up Instruments now to see if anything obvious pops up.

**Comment by corrados** [comment] 2020-05-20 05:07
Yes, sure :-). Good luck!

**Comment by MITEL-UNIUD** [comment] 2020-05-23 21:03
Not sure it is related, however working with an image analysis system (ImageJ) one similar issue appears -slowness-  when the window is not in focus, and apparently it comes from the "app nap" feature of the OS, to save energy.

**Comment by remixmabix** [comment] 2020-05-27 15:50
I confirm that deactivating power nap fix the problem.

**Comment by AronVietti** [comment] 2020-05-27 16:03
OK, this is a great lead, thanks @MITEL-UNIUD and @remixmabix. This may also explain why I can reproduce in the foreground but "idle".

**Comment by AronVietti** [comment] 2020-05-27 16:37
Wrote a quick ObjectiveC interface to call beginActivityWithOptions with NSActivityBackground and NSActivityLatencyCritical. I'll need to test more after work, but this seems to be on the right track. @corrados I used ObjectiveC code, but notice CoreAudio is being used directly from C++. I'm not sure if Apple has a C header for this, if not are you OK with mac only Objective C code and an interface header?

**Comment by corrados** [comment] 2020-05-27 16:40
Do you mean something like this: https://stackoverflow.com/questions/25817616/how-to-disable-os-x-app-nap-in-c

**Comment by AronVietti** [comment] 2020-05-27 16:44
No, that's pulling in the objective c runtime!?!? The standard way to do this is write objective c code to handle the calls, and expose a C compatible interface that you make visible through a separate header for C++ to call. More like this https://stackoverflow.com/questions/41184989/using-nsprocessinfo-from-c

**Comment by AronVietti** [comment] 2020-05-27 16:47
And, preferably this would have better encapsulation and the ability to start and stop the Activity state, so it can be turned off when the client isn't connected or the server is in it's stopped state.

**Comment by remixmabix** [comment] 2020-05-27 17:31
Just another precision/notice and just to sum up :

Deactivating Power Nap with focusing outside Jamulus windows fix the problem but if the Jamulus window is in another "virtual window" then the problem is still there. I notice that I got the same behaviour with Ardour on virtual window changes though. 

But nevermind you fixed my main trouble, many thanks for fixing this issue.

**Comment by corrados** [comment] 2020-05-27 20:35
> if not are you OK with mac only Objective C code and an interface header?

No problem. Just create the new file in the "mac" folder.

**Comment by AronVietti** [comment] 2020-05-27 20:45
Actually did that while testing. :) I should be able to get a PR up tonight.

**Comment by AronVietti** [comment] 2020-05-28 07:43
@corrados PR https://github.com/corrados/jamulus/pull/304 Also found that the stuttering caused periodically for other people, that didn't seem to match this behavior, is caused by location services while streaming over WiFi.

**Comment by corrados** [comment] 2020-05-28 14:46
Do you mean that your code also solves that stuttering?

**Comment by corrados** [comment] 2020-05-28 17:06
The code is merged and the issue should be fixed now. I close this Issue now.

**Closed by corrados** 2020-05-28 17:06 UTC
Labels: bug, development in progress

**Comment by AronVietti** [comment] 2020-05-28 17:28
@corrados No, the stuttering caused by Location Services was not solved by this PR. It interrupts the socket connection for hundreds of milliseconds some times. So the best that could be done would be larger buffers, adding retransmission to the protocol, and some kind of interpolation algorithm for missing packets. Without adding latency I can't see a good way around +100ms blocking on the recvfrom call. I also could find no documentation on turning it off using any Apple API's. Maybe add this to the documentation of OSX?

**Comment by corrados** [comment] 2020-05-28 17:57
Well, the answer to this problem is: Use ethernet :-).

**Comment by AronVietti** [comment] 2020-05-28 18:19
Or turn off location services when using Jamulus, especially when running the server.
