### ISSUE TITLE
Linux client from git core dumps on exit

### ISSUE THREAD

**Issue by elliotclee** [corrados/jamulus#155] opened 2020-04-29 04:48 UTC
To reproduce: run Jamulus client, connect to any server, input meters might show random noise coming in. Click "Disconnect" and then close the client window. Client will either core dump when Disconnect is clicked, or when client exits.

git commit bef58357ef1f8c1138af32a7850d35405f79cfa7 doesn't have the bug. git commit 3427f507adf70feddd448ceec34bb0fddd1b4017 is the first one after that where I could get it to compile and reproduce the bug with.

Let me know if you have any problems reproducing.

**Comment by Snayler** [comment] 2020-04-29 14:54
I believe this is a duplicate of #154

**Comment by corrados** [comment] 2020-04-29 15:21
Yes, it is a duplicate. I will close this one now.

**Closed by corrados** 2020-04-29 15:21 UTC
Labels: bug, duplicate
