### ISSUE TITLE
--clientname does not display in Windows task bar

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#789] opened 2020-12-20 07:53 UTC
Posting on [behalf of forum user](https://sourceforge.net/p/llcon/discussion/developerforum/thread/c49a110a67/#3ad8)

The string given by the `clientname` option displays after "[serverName] - [n] users". This means is can be hidden from view in some circumstances such as the task bar, which defeats the purpose of having it when running multiple clients. 

Suggest that since "[serverName] - [n] users" is also shown on the mixer border, there is no need to show it in the window title too. 

Also a question as to why the clientname string does not show in child windows (eg chat, settings).

**Comment by corrados** [comment] 2020-12-28 09:55
> Suggest that since "[serverName] - [n] users" is also shown on the mixer border, there is no need to show it in the window title too.

The reason for showing it in the window title is: https://github.com/corrados/jamulus/issues/559

> The string given by the clientname option displays after "[serverName] - [n] users". This means is can be hidden from view in some circumstances such as the task bar, which defeats the purpose of having it when running multiple clients.

We can change the order. If --clientname is given, we can show this name at the very beginning so that we get: [clientname] - [serverName] - [n] users.

**Comment by gilgongo** [comment] 2020-12-28 10:32
I guess changing the order would help in cases where the window space is limited.

**Comment by corrados** [comment] 2020-12-29 21:49
This is how it looks now in idle using --clientname TESTING:
![grafik](https://user-images.githubusercontent.com/46655886/103316176-f89ab300-4a27-11eb-9c46-817bab836254.png)
And with an active connection:
![grafik](https://user-images.githubusercontent.com/46655886/103316207-1700ae80-4a28-11eb-9d58-23673f026ddb.png)
Now the "TESTING" is not clipped in the Windows task bar.

**Comment by pgScorpio** [comment] 2021-01-02 00:47
As I am the "forum user" gilgongo mentioned...

I would really plead for an option to set the window titles from the settings (stored in inifile).
Maybe using some format like:
$WindowName = Jamulus|Jamulus-Chat | Jamulus-Settings
$ServerAddress = server[+portnumber]
$Participants = number of participants
$Clientname = clientname passed on comnand line.
Maybe even more...
$TotalLatency, $PingTime, ...?


So everyone can set its own Title format like:
"$Clientname $Servername-$Participants Users $WindowName" would be as you suggested?
and
"$Clientname-$WindowName" or "Guitar-$WindowName" or "Voice-$WindowName" would be more convenient when scripting using window names (more as I would like to see it)

Having this setting option would also end the discussion on how the window title should look like, since everyone can set it's own format.

**Comment by corrados** [comment] 2021-01-06 21:38
Thanks for you comment. But I would like to not make the implementation too complicated. I think what I implemented recently solves the "_it can be hidden from view in some circumstances such as the task bar_". For everyone who does not use the --clientname, nothing is changed (which is good) and for all who are using the --clientname, they now can clearly see their assigned name in the Windows task bar.

**Comment by pgScorpio** [comment] 2021-01-07 13:38
@corrados Sorry to hear this.

I don't think it should be too complicated to implement the custum format and I'm afraid your suggested change will mess up my (and probably others) automation, since my scripts are checking for window names containing "Jamulus <clientname>".

(Already needed to use "containing" because of the serveraddress #users in the title wich is continuously changing)

Off course I could change the scripts to check for "<clientname> Jamulus" but the problem is that those scripts are already in use by almost 50 users and they will have major problems when updating Jamulus to a version using "<clientname> Jamulus" in the title, but it would be no problem if they could just set a custom title of "Jamulus $ClientName".

So please either implement the custom title or change the title to "Jamulus <clientname> server - # users"
(Just moving  "server - # users" to the end instead of at the beginning of the title)

**Comment by corrados** [comment] 2021-01-08 15:46
> my scripts are checking for window names containing "Jamulus clientname"

That is no problem. My new implementation if flexible in this regard. Simply start Jamulus with:

`--clientname "Jamulus myname"`

And tell your script that the Jamulus clientname is `myname`.

**Comment by pgScorpio** [comment] 2021-01-08 17:07
So I still will have to update the scripts of 50 users as soon as they have updated Jamulus ???
That IS a problem for me and my users...

**Comment by corrados** [comment] 2021-01-08 17:13
> but it would be no problem if they could just set a custom title of "Jamulus $ClientName"

I do not understand what your problem is. If you say that your Jamulus users can change the title of Jamulus, this is exactly what you do with the command `--clientname "Jamulus myname"`.

So you just get what you want.

**Comment by pgScorpio** [comment] 2021-01-08 18:29
Let me try to explain....
The users don't run the Jamulus command, they just boot from an USB stick with Jamulus OS and my scripts, or start a script on windows by just clicking a shortcut.
The script starts/stops/activates Jamulus and other apps based on a user selected mode.
Activating/Closing/etc of multiple apps is done based on the window titles... (For Jamulus that is titles containing "Jamulus clientname"). So if the Jamulus title changes in such a way it does no longer contain "Jamulus clientname" I will have to update the scripts (for windows and linux) and  also update all users Windows installations or usb sticks!

The main idea was to have a plug and play  'two click" solution for the users, which have no technical knowledge at all (and this works great until now).

The only minor problem was that the users compain that they can't recognise the  different Jamulus instances on the taskbar because they all start with the same server url.
So my request to you was simple "remove the server url from the window title. (placing it at the end would be ok too though).

I realy appreciate that you are seriously looking into this, but now you want to implement another solution that turns my "minor" problem into a "major" problem!
So please JUST move serveraddress to the end of the title, placing "Jamulus clientname" at the begining, or leave it as it is.

**Comment by corrados** [comment] 2021-01-08 19:06
The easist fix is to introduce some redundancy. So, if --clientname is used, now you have two times "Jamulus" in the title:
![grafik](https://user-images.githubusercontent.com/46655886/104054120-cab62b00-51ec-11eb-9c5d-e710117e9be1.png)

**Comment by pgScorpio** [comment] 2021-01-08 20:04
Sorry, maybe I just don't understand your problem.

I don't see why it would be easier to introduce this redundancy. Why can't you just swap the order ?

`Jamulus [clientname] - server - n users`
instead of
`server - n users - Jamulus [clientname]`
??

**Comment by corrados** [comment] 2021-01-08 20:09
Just fixed that.

**Comment by corrados** [comment] 2021-01-14 15:43
> or change the title to "Jamulus clientname server - # users"

Since this is done now, I'll close this Issue now.

**Closed by corrados** 2021-01-14 15:43 UTC
Labels: bug, improvement
