### ISSUE TITLE
Global chat and maybe even pm chat and maybe users online?

### ISSUE THREAD

**Issue by AndyMcProducer** [corrados/jamulus#569] opened 2020-09-04 23:10 UTC
Please xx xx xx can we have global chat and maybe even pm chat and maybe users online?

????

:P

**Comment by maallyn** [comment] 2020-09-04 23:23
I am confused what this means.

**Comment by AndyMcProducer** [comment] 2020-09-05 15:01
Global chat would be a chat outside of a server and pm would be ability to private message someone else who we see in a server or in the global chat. Users online would be a list showing users who pinged the connect window but if it used some open source irc then that would probs be simpler to show users and do pm. Chat window could just be the gateway to server chat, global and pm chats.

**Comment by AndyMcProducer** [comment] 2020-09-05 15:02
But global chat would be cool even or if not that seeing all users and being able to maybe ping them an invite of which server ya in.

**Comment by gilgongo** [comment] 2020-09-05 16:37
> being able to maybe ping them an invite of which server ya in.

Subject to whether their ping time to that server was viable, of course.

**Comment by trebmuh** [comment] 2020-09-05 17:05
Just saying that I like the idea of having a 'global' chat where people can meet and talk before going into a room together.
I can see someone going there and saying "hey people, who's in for a rock jam session ?" and a few people answering.

**Comment by gilgongo** [comment] 2020-09-05 17:16
I suppose the implication here is that, unlike WhatsApp or one of the many other messaging services out there, your membership of the global chat would be based on you connecting your client to a Jamulus chat server. Your profile would then be your Jamulus profile (handle, country, instrument, skill level). So you don't have to sign up or sign in as with a 3rd party system.

The main problem with the "who's in for a rock jam session" scenario is how to pick a server that has sufficiently low ping times for all the participants. You could imagine some form of "best fit" function that looked at the participants' server lists and suggested a server(s) that had the lowest ping time for all those putting their hand up, I guess.

Intriguing.

**Comment by bflamig** [comment] 2020-09-05 19:15
Along these lines my band members have all commented that besides from being able to have practices and jams, it's really nice that by using Jamulus we can have really natural group conversations where everyone's voice is clear and there are no half-duplex problems of having to wait for someone to stop speaking before others can. Jamulus is worth it just for that! Maybe that's an aspect of Jamulus that can be further developed.

**Comment by corrados** [comment] 2020-11-02 20:33
This is a duplicate of this: https://github.com/corrados/jamulus/issues/571 so, I'll close this issue now.

**Closed by corrados** 2020-11-02 20:33 UTC
Labels: feature request
