### ISSUE TITLE
Central server address

### ISSUE THREAD

**Issue by Lucafeelgood** [corrados/jamulus#251] opened 2020-05-20 09:37 UTC
Is it possible to put the Central Server address menu, that is in settings area, directly in the server list window?

Thanks

**Comment by Snayler** [comment] 2020-05-20 10:21
Duplicate of #157, it will be available in next version.

**Comment by Lucafeelgood** [comment] 2020-05-20 10:35
Ok, sorry, and thanks a lot

**Closed** 2020-05-20 10:40 UTC
