### ISSUE TITLE
Slave Raspberry Pi4 server temporarily looses connection when it registers in the server list 

### ISSUE THREAD

**Issue by brynalf** [corrados/jamulus#752] opened 2020-11-28 14:54 UTC
Jamulus 3.6.1
Slave Raspberry Pi4 server temporarily looses connection when it registers in the server list.
Default interval for registering 15 minutes. 

Consequence:Every 15 minute there is 5-10 s of white noise followed by 5-10 of bad jitter after automatic reconnection.

Proof: I changed row 211 in llcon-jamulus/src/global.h to
define SERVLIST_REGIST_INTERV_MINUTES   1 // minutes
and recompiled which lead to the same behavior but once every minute.

This is probably not only an issue on a Rasberry Pi, but that is where I observed it.

**Comment by corrados** [comment] 2020-11-28 17:52
I have never observed this issue. But since it only happens every 15 minutes, maybe most of the time you blame something else for the drop outs.

I could imagine that the function [fromName](https://doc.qt.io/qt-5/qhostinfo.html#fromName) in function ParseNetworkAddress() makes the problem. This is a blocking function which queries the IP address from the given URL. Can you please do a test for me? Could you please get the IP address of the Central Server (e.g. by using ping) and register to the IP address instead of the URL. It would be interesting if the problem is still there if you are using the IP address.

**Comment by corrados** [comment] 2020-11-28 18:01
I just tested it on my Windows and did the same test as you did (set the register interval to 1 minute) and I cannot reproduce your issue. The audio quality was perfect all the time. The registering did not influence the audio stream at all.

**Comment by brynalf** [comment] 2020-11-28 22:54
I have now also tested it on Windows and have the same experience as you, i.e. no problem. Will test with the Pi as you suggested above.

**Comment by brynalf** [comment] 2020-11-28 23:37
Success! You were right. Using the central server ip number when starting the slave server eliminated the problem.

**Comment by corrados** [comment] 2020-11-29 08:13
Can you please do another test? Checkout the branch [server_register_test](https://github.com/corrados/jamulus/tree/server_register_test) and compile that code. Then please use the URL again and test if the problem is still there.

**Comment by brynalf** [comment] 2020-11-29 15:51
The problem is still there after the test but I am a noob at checking out branches.
Did:
$git pull
$git checkout server_register_test

followed by my usual:

$qmake "CONFIG+=nosound headless" Jamulus.pro
$make clean
$make
$cp Jamulus /usr/local/bin/

**Comment by corrados** [comment] 2020-11-29 18:40
Thanks for testing. Your Git commands look ok.

So, the problem seems not to be that the command is blocking. Maybe the Raspbian OS has a problem resolving the URLs which may consume a lot of CPU or network resources, leading to the issues in the Jamulus server. But this is just guessing...

**Comment by brynalf** [comment] 2020-11-29 20:03
Your comment got me thinking, so I edited
/etc/dhcpcd.conf

to state the closest DNS resolvers of my ISP instead of asking my router for them

static domain_name_servers=...

Now it works to use the URL for the central server. 
No  more loss of connection. 
At least none during a short test with the 1 minute provocation.

**Comment by corrados** [comment] 2020-11-29 20:56
Thanks for sharing your finding. So, the issue was not in the Jamulus software but in the system configuration. Should we close this Issue then?

**Comment by brynalf** [comment] 2020-11-29 21:09
Yes I think we should close it. Thank you for all your help.

**Closed** 2020-11-29 21:21 UTC
Labels: bug

**Comment by brynalf** [comment] 2020-11-29 21:35
Hehe...I found the error. The raspberry pi has 4.4.4.4 as default primary DNS and the local gateway as the secondary DNS.
In Sweden 4.4.4.4 is not reachable or at least resulting in a timeout when pinged.
