### ISSUE TITLE
Mac Aggregate Devices do not work

### ISSUE THREAD

**Issue by mrbell321** [corrados/jamulus#138] opened 2020-04-24 16:11 UTC
Mac OS X lets you configure "Aggregate Devices" that mix two or more actual inputs into a  stream. This is useful to get a microphone and direct in input  
OS X provides a built-in meter so I know that the device is configured properly.
Jamulus recognizes the inputs separately and correctly captures sound.
Jamulus recognizes the aggregate device however no sound is captured from it from either physical input. 
Tested on a 2012 MacBook Air w/ Catalina and a 2012 iMac with High Sierra.

**Comment by corrados** [comment] 2020-05-01 07:10
> Jamulus recognizes the inputs separately and correctly captures sound [...] Jamulus recognizes the aggregate device however no sound is captured from it from either physical input.

This sound like a contradiction. You write "correctly captures sound" and "no sound is captured".
Do you see the input LED meters of Jamulus show active inputs if you are connected to a server (please note that the input LEDs of Jamulus are only enabled if you are in a connection to a Jamulus server)? If this is the case, so the problem is just the audio output side?

**Comment by Snayler** [comment] 2020-05-01 12:35
> This sound like a contradiction. 

I think he's saying that Jamulus correctly captures sounds from the individual devices he's trying to aggregate (example: selecting one device at a time and testing on Jamulus), but it doesn't get any sound if he selects the aggregate device on Jamulus.

**Comment by mrbell321** [comment] 2020-05-01 13:06
Snayler has that right. Sorry for my confusing description.
When using the aggregate device, there are no LEDs or sound output. When
using individual devices, the LEDs and sound works fine.

**Comment by corrados** [comment] 2020-05-01 13:16
Ok, thanks for the clarification. I will try that out on my Mac if I can reproduce the issue.

**Comment by corrados** [comment] 2020-05-01 16:50
I tried it out. What happens when you create an aggregated device is that Jamulus is provided with all channels of each individual audio input. But this is not supported.
But anyway, I think the aggregated device will not give you the desired functionality. As far as I understood your initial post: you want to mix your microphone signal with your instrument signal with the aggregated device. But this is not what Apple does for you. The aggregated device does not mix the channels but just provides the audio application with more input channels. The audio application (in this case Jamulus) would be in charge of mixing the audio signals itself. But this is also not supported in Jamulus.
Is my understanding of your intentions correct?

**Comment by mrbell321** [comment] 2020-05-01 17:13
Yes, I think your understanding of my intentions is correct. It's
interesting that apple does it that way. I wonder what that would be used
for?

**Comment by corrados** [comment] 2020-05-01 17:21
I am not sure.
How many input do your two audio cards have which you aggregated? Do they both have two inputs so that the aggregated device then has 4 inputs?

**Comment by mrbell321** [comment] 2020-05-01 17:30
Oh, that's a good question. I was using a rocksmith guitar usb cable which
I'm pretty sure is just one channel. And physically, the input for the
microphone is part of a TRRS connector, w/ stereo headphones. So
physically, it's one channel. However, I'll try to remember to check this
when I get home tonight.

**Comment by Snayler** [comment] 2020-05-01 17:55
In light of this I had to update the Tricks and Tips wiki page and remove the entry for MacOSX aggregate devices, as I thought it would work but apparently not.

**Comment by corrados** [comment] 2020-05-03 12:23
I just implemented the support for aggregated devices on the master branch in Git. I'll close this issue now. If there are remaining problems on this topic, please re-open the issue.

**Closed by corrados** 2020-05-03 12:23 UTC
Labels: bug, development in progress

**Comment by Snayler** [comment] 2020-05-03 22:16
So does that mean aggregate devices will work again? Can we mix two different sources into Jamulus?

**Comment by corrados** [comment] 2020-05-04 08:01
If you have exactly 4 input channels then you are able to mix them in Jamulus.
