### ISSUE TITLE
When Mac display "sleeps", overall delay increases

### ISSUE THREAD

**Issue by Skeezixes** [corrados/jamulus#260] opened 2020-05-21 18:46 UTC
With just me connected to my server running on my laptop, with the client on the same machine, I observe a Ping time of ~2-3 ms and an Overall Delay of ~22 ms.

However, when the display "sleeps", the lag time increases to over 50 ms and the ping time also increases. If then I wake the display, I can observe that the overall delay will drift back down to ~22 ms. This happens whether a screensaver is set or not.

This could be at the heart of why sound quality, initially very good, has deteriorated over the length of a session.

**Comment by corrados** [comment] 2020-05-21 18:52
I guess this is related to this: https://github.com/corrados/jamulus/issues/23
@AronVietti Since you work on https://github.com/corrados/jamulus/issues/23, can you confirm this?

**Comment by Skeezixes** [comment] 2020-05-21 20:33
I'm running MacOS 10.15.4

**Comment by AronVietti** [comment] 2020-05-22 04:35
@Corrados Confirmed. And appears to be related to #23 possible caused by system calls.

**Comment by corrados** [comment] 2020-06-01 20:38
Since https://github.com/corrados/jamulus/issues/23 is fixed and closed, can we close this Issue as well? Can anybody who saw this issue confirm that the newest Jamulus code fixes this issue?
Unfortunately, there is not yet an official release available which includes the fix. So you would have to compile the latest Git master code to be able to test it.

**Comment by AronVietti** [comment] 2020-06-01 20:58
Yes, #23 also solved this issue on my machine. Would be nice to have someone else confirm though.

**Comment by corrados** [comment] 2020-06-09 19:55
@Skeezixes  Jamulus 3.5.6 is released which contains the fix from AronVietti. Please report here if the new version fixes the issue.

**Comment by Skeezixes** [comment] 2020-06-09 21:54
Problem solved. Nice work.

**Comment by corrados** [comment] 2020-06-10 06:39
Great. Thanks again for the implementation -> closed.

**Closed by corrados** 2020-06-10 06:39 UTC
Labels: bug
