### ISSUE TITLE
"Normalise" button request

### ISSUE THREAD

**Issue by njc235** [corrados/jamulus#622] opened 2020-09-24 03:53 UTC
Would it be possible to code a new button into the client which would normalise all faders to 50% for example. If you join a new server with a lot of users, it can take a while to normalise all faders one by one.

**Comment by corrados** [comment] 2020-09-24 15:06
The "New Client Level" should do the trick.

**Comment by chrisrimple** [comment] 2020-09-24 16:09
@corrados I use New Client Level = 50% all that time, and it's great.  But I think this request is for a button that would set all storedfaderlevel values in the INI (and in memory) to 50.  Maybe a new menu item similar to Clear All Stored Solo Values?

**Comment by njc235** [comment] 2020-09-24 18:07
Maybe I wasn’t clear. I understand the new client level and it is great for controlling new clients joining a room but it’s for when I join a room.

**Comment by dingodoppelt** [comment] 2020-09-24 19:15
If I may add a thought: In issue #599 pljones mentioned a possible "balance" slider which may solve this issue and a few others. It would effectively slide between "solo" and "mute" and everything in between which would allow for a very flexible monitoring

**Comment by corrados** [comment] 2020-09-24 20:56
It seems that the New Client Level does not work as expected. I just tried it out with a "fresh ini file", set the New Client Level to 50 and entered a server where some others were already connected. In contrast to my expectation, all faders were on 100 % when I entered the server but they all were supposed to be at 50 %. I'll look in the code soon to find out what goes wrong there...

**Comment by lesmower** [comment] 2020-09-24 21:24
I always thought that the new client level only addressed a client that entered after you entered a server. Pre-existing clients in a server were not affected. I may be wrong.

 

Les Mower

**Comment by corrados** [comment] 2020-09-25 05:05
No, the intention was that it also applies to a clients when you connect to an occupied server. If the New Client Level would work as intended to, njc235 would get what we want: When he sets New Client Level to 50 and enters a server, all clients (which are not stored in the settings) will get a level of 50 automtically and njc235 must not adjust the level of each client manually.

**Comment by corrados** [comment] 2020-09-25 05:07
I'll change the title now to reflect the new understanding of the problem.

**Comment by njc235** [comment] 2020-09-25 18:04
I still think it would be a good idea to be able to push a button and have everyone reset to a predetermined level ready for a remix.

**Comment by corrados** [comment] 2020-09-26 07:25
The New Client Level actually works as expected. When I did my test and I saw that it did not work was because I was connecting to a server which was older than 3.5.5. For the New Client Level to work correctly, we need a Jamulus server version >= 3.5.5.

**Comment by corrados** [comment] 2020-10-06 11:14
Changed the title back to the original one since with the new client level functionality there was not bug.

**Comment by corrados** [comment] 2020-10-06 11:17
> Maybe I wasn’t clear. I understand the new client level and it is great for controlling new clients joining a room but it’s for when I join a room.
> [...]
> I still think it would be a good idea to be able to push a button and have everyone reset to a predetermined level ready for a remix.

Let's continue to discuss this. So basically, if the server version is sufficiently high, you can use the New Client Level for what you want to achieve. If I understood correctly, if you enter a server and there are clients connected which you have never seen, they should get a fader level of 50 %. If you set the New Client Level to 50 %, this will do this. So the New Client Level will work either when you enter the server or when a new unkown client enters the server.

So actually I do not see a need for an additional button.

**Comment by njc235** [comment] 2020-10-06 12:21
I still think there would be value in a 'normalise' or 'set all faders to x%' would be useful. The new feature to clear stored fader values and the improved reliability of 'new client level' is a vast improvement. However consider where you join a large jam, set a lot of faders to your taste including someone with a low gain input. You later have that same person in your room but they have solved their low gain issues. You suddenly get blasted. Sometimes there are more than one high level fader you need to quickly drag down to save your ears. A quick 12db cut to all would solve this. Perhaps I am the only person to see this as a good feature?

**Comment by chrisrimple** [comment] 2020-10-06 15:39
I can see some value here, with a simplified use case: I jam with various people over a period of weeks.  Then I join a jam night and there are 20 people on the server, all with stored fader values in my INI.  I want an easy way to reset them all to 50%, which New Client Level doesn't do.  So a Reset Faders button/menu item would be handy.  It could be just for the server connections at that time, or it could be like Clear All Stored Solo Values: Clear All Stored Fader Values.

**Comment by houbsta** [comment] 2020-10-25 17:17
For live mixing purposes on WorldJam when new musicians join a server - possibly having been there before but mixed for a different song, even playing different instruments... the sound engineer's first thought is to get all faders to the "new client" level by eye, roughly. A button to reinitialise all faders to the new client level would make this very easy. When a new song is about to start the audio engineer would have just one button to push. It could be a menu option / keyboard shortcut, it doesn't need to be pressed frequently.

As others have mentioned, it's also useful when you join a new server to be able to set everyone to 50% or 70% or whatever your setting is, and then start to make your own mix before you join in. If you have seen people before, the settings from your ini will prevail and you may have seen those clients playing different instruments, or with different local gain...

**Comment by corrados** [comment] 2020-10-26 12:34
> A button to reinitialise all faders to the new client level would make this very easy.

I just checked in the code. Not a big deal at all. I just implemented a new menu entry for it:

![grafik](https://user-images.githubusercontent.com/46655886/97172663-a15e3500-178f-11eb-947a-8cdcce5fa478.png)

It's this commit: https://github.com/corrados/jamulus/commit/a0e02f24ba8b7cd5107a9cbe968458f32542052d

**Comment by houbsta** [comment] 2020-10-26 13:31
Fantastic. Two small changes (with #695) that will really help workflow for live broadcast mixing. Thankyou @corrados I will let you know how I get in on in "real" conditions this coming weekend.

**Comment by corrados** [comment] 2020-10-26 14:02
Yes, please share your feedback here. Since the feature is now implemented, I'll close this issue. But we can still continue the discussion even if it is closed.

**Comment by dingodoppelt** [comment] 2020-10-26 22:23
I really love this feature already and it works great for me.
For my usecase it makes more sense to apply the new client level to every fader but my own to change the mix while keeping my monitoring level constant. I changed that in my fork already. Maybe anybody this can be of use for somebody else.

**Comment by corrados** [comment] 2020-11-15 17:29
> For my usecase it makes more sense to apply the new client level to every fader but my own to change the mix while keeping my monitoring level constant. I changed that in my fork already. Would anybody else find that useful?

@houbsta, @sthenos What do you think about this change? I would like to use @dingodoppelt's change also in the official Jamulus version. I guess that for mixing the Worldjam this does not matter since "my own fader" in that case is the fader of the stream which does not have any input signal anyway. The purpose is to take what comes from the Jamulus server, mix it and send the audio to OBS. So I guess "my own" fader level is irrelevant.

**Comment by gilgongo** [comment] 2020-11-15 21:52
Just going to modify the description of the "New Client Level" setting in the docs. This is currently described as:

"This setting defines the fader level of a newly connected client in percent. If a new musician connects to the current server, they will get the specified initial fader level if no other fader level from a previous connection of that client was already stored."

So can we describe "Set All Faders to New Client Level" as to be used when you enter an occupied server so that you can set all clients (that aren't already known) to that level?

**Comment by dingodoppelt** [comment] 2020-11-16 15:57
@corrados Thanks for considering to merge my patch. I created a pull request if that's ok.
#729

**Comment by corrados** [comment] 2020-11-16 16:05
Ok, thanks. Let's wait for other opinions on that before I merge it.

**Comment by corrados** [comment] 2020-11-16 16:07
@gilgongo 

> Set All Faders to New Client Level" as to be used when you enter an occupied server so that you can set all clients (that aren't already known) to that level

Remove this "that aren't already known" because right now all visible faders on the mixer panel are getting that new level. Maybe we change this in the future that your own fader will not be changed.

**Comment by corrados** [comment] 2020-11-19 15:45
No feedback so far. So I'll merge your pull request now.

**Closed by corrados** 2020-11-19 15:45 UTC
Labels: feature request

**Comment by houbsta** [comment] 2020-11-19 15:59
Yes this is fine, the client level fader is not important for a mixing engineer, they has nothing on their own "client" fader. But it is important that even known clients get reset, because a new song with new members joining, and current connected people possibly changing instruments, means it's most useful to reset every level to the same.

**Comment by corrados** [comment] 2020-11-19 16:53
> But it is important that even known clients get reset [...]

Yes, this is still the case. Just your very own fader will not be changed. All other faders which are active in that session are changed.
