### ISSUE TITLE
Sparking/garbling & delays when using high end mic equipment and audio interface

### ISSUE THREAD

**Issue by gvermag22** [corrados/jamulus#487] opened 2020-08-01 21:29 UTC
Earlier we were testing with low end mics and not using audio interface, but now we have switched to Focusrite scarlett solo (3rd gen) for audio interface and Audio Technica AT2020 XLR interface mic. These are both considered good quality audio equipment and recommended by jamulus team. 

The overall delay in Jamulus setting was showing as 50-60ms. I was using windows and have to enable hardware buffering option in ASIOsetup to get/send proper voice. The other person was using macbook.

However, we hear sparking (phat-phat, b&w movie type background disturbances) and audio garbling now and then, which spoils the whole experience. Please fix these audio issues.  Examples:

____-24_6_76_x_36149-336776-1.wav https://drive.google.com/file/d/1kFHYTWkA3RN08Bh0iJeDoeZqdu6WHQCM/view?usp=sharing : 4:33, 8:05, 13:00 or nearby
____-67_180_105_x_22134-2653-1.wav https://drive.google.com/file/d/1YdMKVz59_e9xVgFyZu3z_hj_Tkp-HuUu/view?usp=sharing : 28:30 onwards

Another issue is that of some extra delay being introduced due to the audio interface. While this delay doesn't show up in the jamulus settings window, it is there and causes sync delay between the drum player and singer. I can say this because when I switched to a usb based mic of Fifine brand the extra delay in the sync was gone and it was like night and day. But the Jamulus overall delay was showing the same.

**Comment by corrados** [comment] 2020-08-02 06:30
> However, we hear sparking (phat-phat, b&w movie type background disturbances) and audio garbling now and then, which spoils the whole experience.

This is not caused by Jamulus but by your internet connection. You should make sure no other device is using your internet during your session. E.g. if you have a phone connected to your WLAN and someone sends a WhatsApp video, you will get such audio garbling.

> Another issue is that of some extra delay being introduced due to the audio interface.

This seems to be either a settings issue (incorrect buffer size setting) or driver issue (using ASIO4All instead of the native ASIO driver of the USB device).

**Comment by gvermag22** [comment] 2020-08-29 17:56
@corrados its unfair to have the requirement that the internet cannot be used by any other application or device in the same household when using jamulus. i'm using a powerline adapter to get LAN connection and my down/up speeds are 200Mbps/5mbps. Even with these speeds, it is sacrilegious to restrict the internet usage for one specific application. This is the weakness of the application and not the internet.

**Comment by gvermag22** [comment] 2020-08-29 17:58
@corrados one person with some technical knowledge told me that it is possible to get rid of these audio issues by having logic for packet replication, something that zoom also does. Why can't we make the software more robust in this regard?

**Comment by WolfganP** [comment] 2020-08-29 21:17
> 
> 
> @corrados its unfair to have the requirement that the internet cannot be used by any other application or device in the same household when using jamulus. i'm using a powerline adapter to get LAN connection and my down/up speeds are 200Mbps/5mbps. Even with these speeds, it is sacrilegious to restrict the internet usage for one specific application. This is the weakness of the application and not the internet.

When analyzing realtime apps, is not just a matter of link speed but latency and jitter. Powerline adapters are not usually a good connection technology outside of casual browsing (just turn on a power tool on the same line and the link goes nuts). Same happens with wifi, it's simply a too noisy link that affects time sensitive traffic a lot, nothing that the app can correct.

**Comment by gilgongo** [comment] 2020-10-29 07:50
@gvermag22 It would be interesting to know whether the issues you have reported here have been improved in the 3.6.0 release.

**Comment by corrados** [comment] 2020-10-31 18:29
> one person with some technical knowledge told me that it is possible to get rid of these audio issues by having logic for packet replication

Thanks gilgongo for posting this info here. Yes, Jamulus 3.6.0 now has implemented a logic for packet replication. It would be good to hear from @gvermag22 if 3.6.0 solves his issue.

**Comment by gilgongo** [comment] 2020-12-14 20:25
Maybe no news is good news? Close for now?

**Comment by corrados** [comment] 2020-12-14 20:28
Yes, let's close this one. @gvermag22 if you still have the issue, please re-open the issue.

**Closed by corrados** 2020-12-14 20:28 UTC
