### ISSUE TITLE
low-res icon issue

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#28] opened 2020-03-30 09:06 UTC
_This issue has been migrated form SourceForge  Created: 2016-10-21_

I happen to be on KDE Neon. Jamulus works great, but the icon in my task-manager is low-res.

![icon-jamulus](https://user-images.githubusercontent.com/4561747/78280922-c51b0e80-7511-11ea-8427-b5a5d9292b5a.png)

**Comment by corrados** [comment] 2020-04-05 18:14
Can anybody using KDE confirm this issue? The issue report is very old and maybe this got fixed in the meanwhile. I cannot reproduce this icon issue on my Ubuntu installation.

**Comment by gilgongo** [comment] 2020-04-05 18:16
@corrados That screenshot is from the ALT+Tab task switcher my Ubuntu (Gnome) 18.04 installation.

**Comment by corrados** [comment] 2020-04-05 18:21
Thanks for the info. I will try that out on my Ubuntu.

**Comment by corrados** [comment] 2020-04-05 20:13
Ok, should be fixed by https://github.com/corrados/jamulus/commit/d12877dc8c120c5241839eeccb0d35a3a4786f76

**Closed by corrados** 2020-04-05 20:13 UTC
