### ISSUE TITLE
Add a button to close the server in the server gui

### ISSUE THREAD

**Issue by ycollet** [corrados/jamulus#369] opened 2020-06-16 15:11 UTC
Actually, on Linux, if I start the server GUI, the server starts. But if I close the GUI, the server stills run in the background.
I need then to do a kill -15 on the server PID to stop it.
A button in the GUI to stop the server shloud be nice.
If you close the GUI without closing the server using this button, then, the server will still run in background mode.

**Comment by corrados** [comment] 2020-06-16 15:13
> But if I close the GUI, the server stills run in the background.

This is not supposed to be. Just if you minimize the server GUI, the server should still run. But if you close the windows with clicking on the cross, it should be terminated.

**Comment by ycollet** [comment] 2020-06-16 15:15
On Fedora, if I close the GUI by clicking on the cross, I still have a server running.
I discover that because I was trying to find the good NAT conf on my router I try several time to start a server.

**Comment by corrados** [comment] 2020-06-16 15:22
I just tried it out on my Ubuntu installation and it works as expected. How do you start the server GUI? In my test I started it from the command line with ./Jamulus -s

**Comment by ycollet** [comment] 2020-06-17 13:34
I start the server like that:
```
$ jamulus -s &
```

**Comment by corrados** [comment] 2020-06-17 17:45
I still cannot reproduce your issue even if I start it exactly the same way as you do. Are you running KDE or Gnome?

**Comment by ycollet** [comment] 2020-06-18 09:25
I am using KDE.
I will try to install lxqt to see if I still have the problem with this window manager

**Comment by AronVietti** [comment] 2020-06-20 21:53
@ycollet Does this still happen if you don't run it in the background? i.e. get rid of the &?

**Comment by ycollet** [comment] 2020-06-22 15:17
When I start jamulus without te '&' and when I close the application by clicking on the cross, I still have jamulus running. I need to hit ctrl+c in the terminal where jamulus is running to be able to get the bash prompt back.

**Comment by corrados** [comment] 2020-07-01 04:55
Can you please try again with the lastest release 3.5.8?

**Comment by ycollet** [comment] 2020-07-01 10:19
Still not.
I ran strace on jamulus but I found no valuable informations.
I will build a debug version of jamulus, run jamulus server in gdb and try to see where is jamulus stuck on I have closed the GUI.

**Comment by ycollet** [comment] 2020-07-01 10:26
So, still not very informative:
```
(gdb) where
#0  0x00007ffff6815b6f in poll () from /lib64/libc.so.6
#1  0x00007ffff5a06ace in g_main_context_iterate.constprop () from /lib64/libglib-2.0.so.0
#2  0x00007ffff5a06c03 in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#3  0x00007ffff6ee0b73 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Core.so.5
#4  0x00007ffff6e9391b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Core.so.5
#5  0x00007ffff6e9b5a6 in QCoreApplication::exec() () from /lib64/libQt5Core.so.5
#6  0x00005555555839d8 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:693
```
And the jamulus code:
```
#6  0x00005555555839d8 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:693
693                     pApp->exec();
(gdb) list
688                     if ( !bStartMinimized )
689                     {
690                         ServerDlg.show();
691                     }
692
693                     pApp->exec();
694                 }
695                 else
696     #endif
697                 {
```

I compiled jamulus with gcc 9 / 10 and with fedora specific flags:
```
-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
```
I will try with default jamulus flags to see if the problem comes from here ...

**Comment by corrados** [comment] 2020-07-01 14:13
Thanks for debugging the problem. Hopefully you will find the actual source of the problem so we can fix it.

**Comment by corrados** [comment] 2020-07-12 09:03
Any updates on the investigations?

**Comment by ycollet** [comment] 2020-07-12 09:25
Not yet :)
I've tested flags and various things but no hint yet.
Whet version of Qt do you use ?
Here, it's 5.13.2.

**Comment by corrados** [comment] 2020-07-12 20:29
> I just tried it out on my Ubuntu installation and it works as expected.

On that Ubuntu installation I have version 5.12.4 installed.

**Comment by corrados** [comment] 2020-09-20 18:13
@ycollet What shall we do with this Issue? I have not heard from others having the same problem as you observed.

**Comment by ycollet** [comment] 2020-09-20 18:20
I will have a check tomorrow with the last release.
I will give you some more new tomorrow.

**Comment by ycollet** [comment] 2020-09-23 13:14
Tested on Fedora 32 and I still have the same problem here (with the last release of Jamulus).
The version of qt5 installed on  Fedora 32 is 5.14.2.

**Comment by corrados** [comment] 2020-09-24 14:43
Can you try to start the Jamulus server with specifying an explicit ini-file? Maybe the server GUI tries to save the settings in the file and get's stuck somehow. So you could start it with:
./Jamulus -s --inifile ~/myinifiletest.ini

**Comment by ycollet** [comment] 2020-09-24 15:08
It does not work.
I will have a look at the patches Fedora have applied on qt5. Maybe the problem is related to the qt5 version for Fedora.

**Comment by corrados** [comment] 2020-10-07 15:23
What you could do is to checkout version 3.5.2 from Jamulus Git (this is the last version which supports Qt4) and install the Qt4 devel packets on your Fedora system. Then you should compile Jamulus with Qt4 qmake. If the problem is still there with Qt4, you know that the issue is not caused by Qt.

**Comment by ycollet** [comment] 2020-10-09 21:25
I just tested with qt4 (jamulus 3.5.2) and it works fine.

**Comment by corrados** [comment] 2020-10-10 10:37
Thanks for testing. That indicates that the problem is related to Qt5 on your system.

**Comment by corrados** [comment] 2020-11-02 20:49
Since the problem is Qt related and only occurs on Fedora Linux, is it ok to close this Issue now?

**Comment by corrados** [comment] 2020-11-16 18:11
14 days no responce -> I'll close it now. If anything is unclear or open, just create a new Issue or re-open this one.

**Closed by corrados** 2020-11-16 18:11 UTC
Labels: bug

**Comment by ycollet** [comment] 2020-11-16 19:58
Yes, Sorry, it's time to close the bug report :)
