### ISSUE TITLE
Assign individual output channel to each musician

### ISSUE THREAD

**Issue by Alberstein8** [corrados/jamulus#414] opened 2020-06-30 18:05 UTC
I've been playing with online broadcast of live concerts with Jamulus. We used Reaper DAW to get the output from Jamulus, apply effects and even send sound to OBS to mix with video and broadcast to Youtube. Actually, we were the first Choir to perform a live online concert in Spain, as far as I know. But I'd appreciate to get individals channels from Jamulus to Reaper, one per track. Now, assigning Reaper Rearoute ASIO driver, only a single L/R signal is received in Reaper with all instrument together. But if each channel could be assigned to different Rearoute channels, we could mix the signals in Reaper individually. See image about assigning Rearoute channels to output.
![imagen](https://user-images.githubusercontent.com/9966701/86160752-83980080-bb0c-11ea-8db7-02095c2c9e8b.png)

The idea is doing this for each channel instead of global configuration.

**Comment by corrados** [comment] 2020-06-30 18:10
Isn't it a duplicate of https://github.com/corrados/jamulus/issues/96?

**Comment by Alberstein8** [comment] 2020-07-01 21:03
#96 seems to be about having different configuration of the input channels and mono/stereo, for cases where one person uses several instruments/mics. My request is about being able to configure each channel's output, so channels from other people can be rerouted to Reaper like single tracks. But I supousse in the end it's all about being able to configure each channel input/output independently.

**Comment by corrados** [comment] 2020-07-02 13:53
The design principle is that each client just sends one stream up and downloads one stream. Just the server has all streams available and does the mixing. Sending multiple streams to the client would increase the network load on the server and client significantly. So this is nothing we want to have.

But there are alternatives. You could check out [JamKazam](https://www.jamkazam.com). As far as I understand, they transmit all streams to all clients. Therefore you have all separate streams available at the client.

**Comment by Alberstein8** [comment] 2020-07-02 15:02
Hi,
The idea is not sending/receiving several streams but assigning each channel to different devices or audio channels. But his would happen only in the client Pc. Communication with server would remain as is now, I don’t really know if this is feasible. Assigning to different channels or audio devices would allow to send it to other programs running in the pc, like reaper. 

Alberto

Enviado desde mi iPhone

**Comment by corrados** [comment] 2020-07-02 15:07
> But I'd appreciate to get individals channels from Jamulus to Reaper, one per track. [...]
> The idea is not sending/receiving several streams but assigning each channel to different devices or audio channels.

Ok, then I have not understood your request. If you want to stream each connected client (e.g. if 10 musicians are connected to the Jamulus server you will have 10 streams) to Reaper, you need all individual audio streams of each musician available at the client, right?

**Comment by Alberstein8** [comment] 2020-07-02 15:16
Exactly. I assumed each channel can be managed independently in each client as tracks can be muted, panned etc. Or maybe is the server who changes volumes and pan and send the new mix to the client as a one single stream?

Enviado desde mi iPhone

**Comment by corrados** [comment] 2020-07-02 15:32
> Or maybe is the server who changes volumes and pan and send the new mix to the client as a one single stream?

That's whats happening. All level change, mute, pan is calculated in the server.

**Comment by Alberstein8** [comment] 2020-07-02 17:36
Ok, understood. Then it cannot be made at client side. Maybe server could do it!

Enviado desde mi iPhone

**Comment by corrados** [comment] 2020-07-02 17:39
There is an Issue for that already: https://github.com/corrados/jamulus/issues/146

Shall we close this one now?

**Comment by Alberstein8** [comment] 2020-07-02 17:41
Yes, of course. 

Thanks. 

Enviado desde mi iPhone

**Closed** 2020-07-02 17:49 UTC
