### ISSUE TITLE
Can't use Alesis Asio driver

### ISSUE THREAD

**Issue by Lucafeelgood** [corrados/jamulus#250] opened 2020-05-20 09:32 UTC
Hello, I can't use Alesis Asio driver of Alesis io|26 firewire sound card.

Thanks and regards

**Comment by Snayler** [comment] 2020-05-20 10:20
What errors are you getting? Describe what's happening.

**Comment by Lucafeelgood** [comment] 2020-05-20 10:26
All Jamulus processes, like open a window or change input channel, become dramatically slow, like 5 seconds to open menu. And also latency increase of hundreds

**Comment by Snayler** [comment] 2020-05-20 10:35
Try using Jack to drive the audio card instead. [Jack on Windows](https://jackaudio.org/faq/jack_on_windows.html)

**Comment by Lucafeelgood** [comment] 2020-05-20 11:00
Should I uninstall ASIO4ALL? Is it better in terms of latency than ASIO4ALL?

**Comment by Snayler** [comment] 2020-05-20 11:31
You shouldn't be using ASIO4ALL at all, given that the manufacturer provides a driver for that interface. Try Jamulus with the manufacturer driver.

**Comment by Lucafeelgood** [comment] 2020-05-20 11:38
The manufacturer driver give me the problem I told first. At the moment I'm using ASIO4ALL. So I uninstall ASIO4ALL and I try to use Jack and check if it is better. Thanks

**Comment by Snayler** [comment] 2020-05-20 11:42
Jack is not a driver, you need a driver installed to make it work. If the manufacturer driver doesn't work, then try ASIO4ALL.

**Comment by Lucafeelgood** [comment] 2020-05-20 11:51
I still have the manufacturer driver installed, but I use ASIO4ALL  in Jamulus for the reason I told. If I get some improvement I can try Jack with manufacturer driver, if no improvement I'll come back  to ASIO4ALL. It's ok? Or is it a usefull try?

**Comment by corrados** [comment] 2020-05-22 16:42
Any updates here? Does this Issue needs to stay open or can it be closed?

**Comment by corrados** [comment] 2020-06-01 20:49
It's 10 days ago now and we got no feedback. I will close this Issue now. If the Issue is still relevant, just re-open it.

**Closed by corrados** 2020-06-01 20:49 UTC
