### ISSUE TITLE
Missing Barbershop voice part "Lead" as an instrument // pictures m/f compatible

### ISSUE THREAD

**Issue by klingstar** [corrados/jamulus#702] opened 2020-10-29 15:54 UTC
Dear developers of this fantastic tool Jamulus, 
in Barbershop singing, the voice parts Bass, Bariton, Lead and Tenor are sung by men and women. Would it be possible to create an instrument "Lead" and to make the pictures for all voice parts compatible for both men and women? Ok, it's a "nice to have"...
Thanks and best regards!

**Comment by chrisrimple** [comment] 2020-10-29 16:00
@klingstar This already exists.  In the Jamulus client, open your Profile, click on Instrument, and scroll to the bottom of the list where "Vocal" appears.

**Comment by corrados** [comment] 2020-10-31 12:41
Yes, this is true. The "Vocal" was supposed to be the Lead singer. So I think we can close this Issue now, ok?

**Comment by klingstar** [comment] 2020-11-02 10:16
Hi corrados,
my desire was to have an instrument "Gesang Lead" in the German language version, so that it fits in the alphabetic column together with the other "Gesang ..." instruments, similar to the "Vocal ..." column in the English version. This would be helpful to sort the voice parts of the choir from left to right on the display. 
Thanks and best regards,
Gerd

**Comment by corrados** [comment] 2020-11-02 16:56
But isn't it "Gesang" in the German translation already:
![grafik](https://user-images.githubusercontent.com/46655886/97895921-afcec280-1d34-11eb-87c6-b636ce873b95.png)

**Comment by chrisrimple** [comment] 2020-11-02 17:31
It looks like the German translation may be missing one?  Gesang Lead?  Here's what I see for English...

![image](https://user-images.githubusercontent.com/47258736/97899412-1f6d8f00-1cee-11eb-850c-aac95c6fdcca.png)

**Comment by corrados** [comment] 2020-11-02 19:44
Ah, now I see what the problem is. I have translated it as "Leadsänger". So I have just changed the German translation:
![grafik](https://user-images.githubusercontent.com/46655886/97911771-1d3a1d80-1d4c-11eb-9bb8-621e5d7fc7cd.png)
So I'll close this issue now.

**Closed by corrados** 2020-11-02 19:44 UTC
