### ISSUE TITLE
Feature request: Server "calendar"

### ISSUE THREAD

**Issue by Andrew999999** [corrados/jamulus#768] opened 2020-12-06 21:27 UTC
Has any consideration been given to adding an optional "linked calendar" property to the server - and making a link to it visible on the central server list, if present, alongside "Musicians", "Location" etc.?

I'm thinking that this could be used to link to e.g. a public Google calendar maintained by whoever owns the server, and that shows when public groups are planning to jam. This would be great for public servers - currently there may be no one playing on a good server near you, but there's no way to easily tell when people might be planning to.

This would require a new Server command line/ini item, with a property to allow a URL to be stored.  It would also require the "Connection Setup" dialog to include this property as a column - either by listing the URL explicitly, or by providing a button to click when the URL is present.  

In fact the URL could just as easily link to an arbitrary web page e.g. to give more information about the use of the server, as well as its calendar of sessions.

--Andrew

**Comment by ann0see** [comment] 2020-12-06 22:29
I don’t think Volker would like to integrate this feature. You could nevertheless use the welcome message with a link to a calendar.

**Comment by Andrew999999** [comment] 2020-12-07 08:03
I do that already, but it means connecting to each server in turn to discover three information (or discover three isn't any).  This is not only a bad experience, but problematic if the server is in use.

**Comment by pljones** [comment] 2020-12-07 22:13
Anyone who wants to set up a central calendar can.

Any server operator who wants to add a link on their welcome screen can.

Any user who wants to put entries in the calendar for that server then can do so.

No change needed.

**Comment by corrados** [comment] 2020-12-08 16:09
I agree with pljones. BTW: We already have a web page for this purpose: https://musicianslounge.muziguide.com

**Comment by ann0see** [comment] 2020-12-08 16:35
@gilgongo This site would be something for the new knowledge base too (I don't know what to write, but maybe the creator of this site could)

**Comment by gene96817** [comment] 2020-12-08 20:15
who maintains https://musicianslounge.muziguide.com/? It doesn't work for me. There is not contact information on that webpage.

**Comment by gilgongo** [comment] 2020-12-08 22:42
@ann0see Yes, particularly if people link to it ...

BTW I wonder if we could persuade the creator of the Lounge to put in on jamulus.io as we have done for https://explorer.jamulus.io ?

**Comment by ann0see** [comment] 2020-12-08 22:50
@gilgongo Only if the page really works well and there are no big issues. (The Jamulus explorer does work very well and is an integral part of the community in my opinion)

**Comment by gilgongo** [comment] 2020-12-08 22:52
Yes, I must admit I've not tried the Lounge.

**Comment by corrados** [comment] 2020-12-09 16:54
> BTW I wonder if we could persuade the creator of the Lounge

@interogativ Since you are the creator of the musicianslounge, can you please comment?

**Comment by interogativ** [comment] 2020-12-09 17:33
I wrote musicianslounge a couple of months ago, at the request of someone wanting a 'musicians lounge', It seems to work fine and so I haven't had to maintain it.  A calendar control could be added, but I'd need a lot more specifics on what exactly it was supposed to do and  and how it would get updated.  I have no objection to moving the site to jamulus.io, but I'd need to know more about the hosting environment there, as this site is written in c# for ASP Core.NET 3.1.  It may be able to run on Linux machines, as MS claims, but I haven't tried it.

**Comment by gene96817** [comment] 2020-12-09 18:37
@interogativ    I visited the webpage to give it a try. I could not make an entry to the whiteboard.

**Comment by interogativ** [comment] 2020-12-09 21:48
There's definitely a bug somewhere,  when I visited the page a few minutes ago, I couldn't select the Whiteboard,  even though someone else had already posted a message there.  I pulled up the code on my computer and was debugging it and decided to try the site again and it worked perfectly, without anything having changed on my part.  If I can reproduce the problem, I can debug it. In the mean time, I'd say wait about a minute or two and try the site again.

**Comment by gilgongo** [comment] 2020-12-10 15:06
@interogativ Sorry - I wasn't clear: I meant simply have it respond to a subdomain on jamulus.io in the DNS. It would be hosted in the same place as it is now but respond to https://lounge.jamulus.io, for example.

**Comment by gene96817** [comment] 2020-12-10 18:29
I visited lounge,jamulus.io again with better resiults. It is a good starting point, especially if the whiteboard leaves postings up to 30 days. I think this function is especially valuable for occasional users because those are the ones that are more likely to be seeking additional jamming opportunities.

**Comment by interogativ** [comment] 2020-12-10 18:34
I have absolutely no problem with that.  You can DNS away, however, the site uses SSL and the webserver will need a certificate for the new DNS address.  Since I don't manage the jamulus.io domain, I'd need for an admin there to generate that certificate for "lounge.jamulus.io" so I could install it on the webserver.

**Comment by gilgongo** [comment] 2020-12-10 20:38
@interogativ OK lounge.jamulus.io is set up so if you can get the SSL sorted out we can link to it.

**Comment by interogativ** [comment] 2020-12-10 22:17
OK, to communicate on the SSL setup, you can email me at jamulus@muziguide.com,  I'll send you my email address from there.

**Comment by gilgongo** [comment] 2020-12-14 19:08
@corrados If you could update that link on the central server that would be good (there's a small chance that we might get some backlink benefit from it if somebody links to it from their site).

**Comment by corrados** [comment] 2020-12-14 19:13
Sure, it's already done.

**Comment by gilgongo** [comment] 2020-12-30 15:51
@Andrew999999 does https://lounge.jamulus.io address the issue you have with finding and scheduling jams?

**Comment by corrados** [comment] 2021-01-03 11:18
Since we have a solution with the lounge.jamulus.io to musicians to find each other, I'll close this issue now.

**Closed by corrados** 2021-01-03 11:18 UTC
Labels: documentation
