### ISSUE TITLE
client logon for servers 

### ISSUE THREAD

**Issue by kezzy1966** [corrados/jamulus#607] opened 2020-09-20 09:08 UTC
I cannot see this an existing suggestion but surely it must have been mentioned before.

As more musicians discover Jamulus, could we have a simple logon function on servers please. 

Even when groups kindly put their servers up for public use they often want to use it themselves at a set time per week. Even if logon could be switched off and on just for that period. Also for a unlisted server, we might want to control who can access it in case the address is leaked out. These servers are valuable assets.

Surely this is an established code that could be dropped in ? Or perhaps there is another way to control logon ?

**Comment by corrados** [comment] 2020-09-20 09:23
See here: https://github.com/corrados/jamulus/issues/596, here: https://github.com/corrados/jamulus/issues/521 and here https://github.com/corrados/jamulus/issues/299.

**Comment by gilgongo** [comment] 2020-09-20 17:36
@kezzy1966 Don't forget that if you and your band mates all solo each other, then you won't hear anyone else (and you can always leave a note in the chat to explain that you are having a private session). Other people will see that you can't hear them.

**Comment by corrados** [comment] 2020-09-20 18:06
Since this is duplicate of https://github.com/corrados/jamulus/issues/299, I'll close this Issue. Please continue the discussion in the existing Issue.

**Closed by corrados** 2020-09-20 18:06 UTC
Labels: duplicate
