### ISSUE TITLE
Server recordings aren't real-time accurate

### ISSUE THREAD

**Issue by barkingcats** [corrados/jamulus#401] opened 2020-06-28 06:21 UTC
Summary: Per-track recordings on the server can have more or less than 48,000 samples per real-time minute. 

Detail: 
1) Create a test audio track with a 1000hz test tone and overlaid 120bpm click, at least 1 minute long, with, say, Logic Pro
2) Connect to a Jamulus server with server recording enabled
3) Play the test track. Disconnect from the server when complete.
4) Import the server-recorded .wav file into the Logic Pro project. Line up the start of the test section in the .wav file with the original test audio, using the click as a marker. 
5) scroll down the timeline bar by bar, viewing both tracks simultaneously

Expected result: both tracks are reasonably identical, with the click staying in sync for the full length

Actual result: the .wav file stays in sync for awhile, then jumps off. If you scroll backward from the first out-of-sync point, you'll find a location where a chunk of samples have been dropped and smoothed over. The attached screenshots show missing sections of the Jamulus recording versus the original. In one case, the .wav file periodically had 128 added samples, so it was too long, versus too short. 

Why it matters: I have rhythm backing tracks of my band that we use for rehearsal. I'd like to use the Jamulus rehearsal recordings to fill in the backing tracks to get full ensemble recordings. If the Jamulus recordings add or drop samples, they don't sync and cannot be used. 

Jamulus 3.5.6 server on Windows 10, 3.5.6 client on MacOS

![Screen Shot 2020-06-27 at 11 14 52 PM](https://user-images.githubusercontent.com/25629765/85939733-c9ff1c80-b8cc-11ea-9c36-a9119c50764c.png)
![Screen Shot 2020-06-27 at 11 16 24 PM](https://user-images.githubusercontent.com/25629765/85939734-ca97b300-b8cc-11ea-92b3-b2b614b7e409.png)
![Screen Shot 2020-06-27 at 11 17 54 PM](https://user-images.githubusercontent.com/25629765/85939735-ca97b300-b8cc-11ea-87a4-b34e1ae18dee.png)
![Screen Shot 2020-06-27 at 11 18 13 PM](https://user-images.githubusercontent.com/25629765/85939736-cb304980-b8cc-11ea-83c6-e464c7caa47f.png)
![Screen Shot 2020-06-27 at 11 18 39 PM](https://user-images.githubusercontent.com/25629765/85939737-cb304980-b8cc-11ea-98c1-bac8d190cf6f.png)

**Comment by corrados** [comment] 2020-06-28 06:53
Jamulus has to use network buffers (jitter buffers) to deal with the fact that network packet arrival time is not 100% perfect. Sometimes it can happen that one or more network packets get lost. In that case the used audio codec (OPUS codec) tries to interpolate missing packets (I think that is the smoothing you observed).

**Comment by barkingcats** [comment] 2020-06-28 07:47
I understand packets getting lost, though it's interesting that there was a case where extra packets seemed to be getting found. The OPUS documentation talks about packet loss concealment, but doesn't obviously mention sample-accurate streams vs smoothing. 

For what it's worth, these test cases were generated with a Mac client talking to a Windows server on the same gigabit switch, 0-1ms ping times, local and server jitter buffers of 2. The first two examples lost 357-358 samples, about 7.5ms. That seems like a lot for what should be a low-latency situation.

**Comment by pljones** [comment] 2020-06-28 07:51
If possible could you do a further test connecting two clients and recording on one of the clients the signal received from the other and compare?

**Comment by barkingcats** [comment] 2020-06-29 02:37
I connected two Mac clients with a separate server, all 3.5.7, default settings. Client 1 played the 2 min test file, client 2 and the server both recorded it. The attached images show the original track and the two recordings. 

The track recorded on the client jittered back and forth a little, but wasn't bad. The server recording immediately started lagging, was short by 7,680 samples after 2 minutes. 

Read through #234 after my original post last night. Got lost in all the detail, but it sounded similar, especially if the missing bits are inconsistent from session to session. 

![Recording lag 1](https://user-images.githubusercontent.com/25629765/85966773-99bf8880-b975-11ea-8e21-509e55afe3ee.png)
![Recording lag 2](https://user-images.githubusercontent.com/25629765/85966775-9a581f00-b975-11ea-8da9-61d25bccc9d9.png)
![Recording lag 3](https://user-images.githubusercontent.com/25629765/85966777-9a581f00-b975-11ea-9ad3-36b1e16dd3ba.png)
![Recording lag 4](https://user-images.githubusercontent.com/25629765/85966778-9af0b580-b975-11ea-856e-d7fef9dca78e.png)

**Comment by pljones** [comment] 2020-06-29 07:26
Thanks!  Really helpful.  As the signal is passing through the server from client 1 to client 2 (pretty much) unaffected, this isolates the problem to somewhere either between the server and recorder or in the recorder itself, which is what #234 had outstanding, I think.  Now we've got this clear picture, I'll stop worrying about #234, as the main part was resolved and deal with the outstanding part off this issue.

**Comment by pljones** [comment] 2020-07-04 16:36
OK, I've tried this set up:

Linux box running
- a private server, recording sessions
- a client connected to the private server
- Audacity generating the click track routed through the client

Windows box running
- Reaper, recording Jamulus output
- a client connected to the private server

I kicked off recording in Reaper, started a fresh recording session on the server and hit play in Audacity.  After about a minute, I stopped Audacity and stopped the server and Reaper recordings.

I thus had three audio files
- client to client (Reaper)
- client to server recording
- original clip

I loaded all three up in Reaper and aligned the two recordings to the start of the original clip to the sample.

Just before 47 second in, there's a strong metro click (the track order is as listed above):
![image](https://user-images.githubusercontent.com/1549463/86516815-8439db00-be1b-11ea-9978-39667c3aed75.png)
So, zooming in:
![image](https://user-images.githubusercontent.com/1549463/86516847-e7c40880-be1b-11ea-8d7b-bc1d35713c1c.png)
Client to client has obviously lost more data than client to server, as it's showing the audio "earlier" than the original clip.  Client to server is pretty close, though.

The very last click is just over a minute into the recording:
![image](https://user-images.githubusercontent.com/1549463/86516876-4ab59f80-be1c-11ea-9812-3b6480e1e17e.png)
Zooming in really close on the client to client (top) and client to server recording (second):
![image](https://user-images.githubusercontent.com/1549463/86516916-95371c00-be1c-11ea-986a-56f45eff09c4.png)
Looks like somehow things got back in alignment!

@corrados, I don't think there's an issue here.  Can you comment?

**Comment by corrados** [comment] 2020-07-05 08:51
> @corrados, I don't think there's an issue here. Can you comment?

I must admit that I have never done recording myself and I have also not looked in detail at your recording code. So I think I am the wrong person to judge this...
Just one possible hint: It seems that people reporting issues use MacOS. Maybe it is OS dependent?

**Comment by pljones** [comment] 2020-07-05 11:33
@corrados:
The only "weird" thing is that the client-to-client recording is "shorter" than the original...  I've not counted exactly but I'm guessing it'll be a multiple of the buffer length (i.e. probably 64 samples here).

One of the things the recorder _doesn't_ know is whether there's been a dropped packet.  But it may be that the receiving client also doesn't know this -- and, indeed, the server may be ignoring the situation.  I've not looked at the code around delay / jitter buffering closely as it's complex and I hadn't needed to understand it.

> UDP uses a simple transmission model that doesn't include handshaking dialogues to provide reliability, ordering or data integrity

So I was wondering whether -- and if so how -- packet _order_ and _completeness_ are identified by the server -- is there any serial id on a client's packets that would allow for this?

**Comment by corrados** [comment] 2020-07-05 11:43
The drop out UDP packets do not matter for the jam recorder. The jam recorder just stores the audio which is used at the server for creating the mix. This is what all clients will hear. And this is the purpose of the jam recorder: To record what all clients will hear.

**Comment by corrados** [comment] 2020-07-05 11:45
I guess I know what is the issue. The jitter buffers by design can have a varying delay depending on the position of the put/get pointers in the buffer. So you will always get a slightly varying latency of each clients audio signal. But again, the purpose of the jam recorder is to record what all clients hear. And this is what it does, right?

**Comment by pljones** [comment] 2020-07-05 12:15
Yes - that's what I'm seeing above.  The only significant difference is between the original signal and that recorded (by both client and server).

I guess I'm wondering if that difference would have increased over time, which is potentially what @barkingcats is seeing.

**Comment by corrados** [comment] 2020-07-05 12:20
That can happen. The timer in the server is driven by the OS clock. The client is driven by the clock from the sound card. These are not synchronized. If, e.g., the sample clock of the sound card is a bit off, you will get a difference which increases over time. I fear this is something we cannot do much against it.

**Comment by pljones** [comment] 2020-07-05 12:20
It records one frame from each client on each "cycle".  If it gets a second frame from a client, it assumes that's the start of a new "cycle" and moves all clients on to the next "cycle".  If one of the clients didn't get a frame in during a cycle, the recorder will record less audio for that client.  So recordings can "shrink" if frames aren't received for all clients "in order".  The way I understood the processing in server.cpp to work, it cycles (hence "cycle" above) through all connections, processing a frame - this gets sent to the recorder.

**Comment by pljones** [comment] 2020-07-05 12:22
I don't think there's much without adding a frame serial number to the protocol and using that in addition to the jitter buffer to ensure completeness.  If a missing frame is identified, it would need substituting some how (ideally "smoothly") and processing in place of the missed frame.

**Comment by corrados** [comment] 2020-07-05 12:33
This is what's done. If a packet is lost, we substitute a packet and the OPUS codec tries to interpolate. So each time the server timer triggers, an audio block from each client is available. And all of these are shipped to the jam recorder. So if a client has a "connected" state at the server, you will always get audio blocks from that client in your jam recorder.

**Comment by pljones** [comment] 2020-07-05 12:47
Ah right, in that case, I don't think there is anything else that could be done.

**Comment by barkingcats** [comment] 2020-07-05 18:23
Where's the code that does the physical write-to-file? If it's somewhere you have control over, what about saving the start time per client, keeping track of the number of samples written, and topping up the write buffer periodically? If you've been writing to the file for 10 seconds, you should have written 480k samples. If it's less than that, zero-fill to get to that number. 

If it's more than that, I suppose do nothing with the expectation that something will get lost later.

**Comment by corrados** [comment] 2020-07-05 18:27
That will not help. The server timer is triggered by the same system time as you would query this "start time per client". So I expect that after 10 seconds you will always have the correct number of samples. The problem is the difference between the clock of the server and the oscillator in the sound card of the client. You would have to get this difference.

**Comment by barkingcats** [comment] 2020-07-05 20:08
It would be surprising if the clocks were that different. I measured 7,680 samples missing after 2 minutes; or 0.13%. I'd expect an order of magnitude better accuracy than that.

**Comment by pljones** [comment] 2020-07-05 21:01
@barkingcats Did you generate the audio on the client PC prior to sending it or on an external device playing live?  I've no way to compare those two situations, unfortunately but I'd be interested in seeing the "recorded locally" for an "external device playing live" compared to the client-to-client recording for the same session.

What I did was synthesised the audio and then played that back using Jack with the "dummy" driver, so no sound card clock involved.  The remote client and server remained synchronised but the was a small discrepancy against the original track, far less than you're seeing (after 1 minute, that is).

**Comment by barkingcats** [comment] 2020-07-06 18:34
I set up a test tone track in Logic, then recorded it and the click to a new audio file. I then played that audio file from Logic: Logic->Loopback->Jamulus.

I'll see what Jack looks like on Mac and see if I can remove Logic and Loopback from the equation. I can also try running Jamulus Server on a different machine.

**Comment by pljones** [comment] 2020-08-09 16:12
Hi @barkingcats,

I guess as this was a month ago, there haven't been any issues since?  Can this be closed?

Thanks,

-- Peter

**Comment by corrados** [comment] 2020-08-20 08:51
No feedback... I'll close this now. @barkingcats if you still think we can do something in the Jamulus software to improve the situation, just re-open this Issue again.

**Closed by corrados** 2020-08-20 08:51 UTC
Labels: bug
