### ISSUE TITLE
segmentation fault (server 3.5.11)

### ISSUE THREAD

**Issue by mawess** [corrados/jamulus#618] opened 2020-09-22 19:43 UTC
Got a segmentation fault in the server tonight (my first! all previous version the since April has worked (almost) perfectly)

server version 3.5.11
replaced some possibly sensitive data with [...]

6 clients connected. denoted as a b, c , x and y.

Last login: Sun Sep 20 10:47:29 on ttys000
[...] ~ % ./JamulusServer.txt
Password:
- maximum number of channels: 50
- using 64 samples frame size mode
- selected port number: 22125
- recording directory name: ./jamulusrec
Recording state enabled
2020-09-22 16:55:24, yyy.yyy.yyy.yyy, connected (1)
2020-09-22 16:55:35,, server idling -------------------------------------
Session RPP: "/Users/ [...].rpp"
Session LOF: "/Users/ [...].lof"
2020-09-22 17:26:37, aaa.aaa.aaa.aaa, connected (1)
2020-09-22 17:29:04,, server idling -------------------------------------
Session RPP: "/Users/[...].rpp"
Session LOF: "/Users/ [...].lof"
2020-09-22 17:58:25, aaa.aaa.aaa.aaa, connected (1)
2020-09-22 18:20:15, bbb.bbb.bbb.bbb, connected (2)
2020-09-22 18:30:41, ccc.ccc.ccc.ccc, connected (3)
2020-09-22 18:38:42, yyy.yyy.yyy.yyy connected (4)
2020-09-22 18:51:07, xxx.xxxx.xxx.xxx, connected (5)
2020-09-22 19:09:14, yyy.yyy.yyy.yyy, connected (6)
2020-09-22 19:09:47, yyy.yyy.yyy.yyy, connected (5)
2020-09-22 19:09:47, yyy.yyy.yyy.yyy, connected (5)
2020-09-22 19:09:47, yyy.yyy.yyy.yyy, connected (5)
./JamulusServer.txt: line 1: 46920 Segmentation fault: 11  sudo nice -n -20 /Applications/JamulusServer.app/Contents/MacOS/JamulusServer -u 50 -F -p 22125 -R ./jamulusrec
[...] ~ %

**Comment by corrados** [comment] 2020-09-22 20:04
This seems to be the same as: https://github.com/corrados/jamulus/issues/480.

I was hoping we had fixed that. Anyway, I think this bug is very hard to reproduce. But here are similarities I can find in the settings/logs:

- in both cases the recording was enabled
- in both cases a user was connecting/disconnecting quickly in a short period of time

@pljones Do you think it could be related to the recording functionality? I do not use the recording and I never had a segmentation fault on my servers.

**Comment by mawess** [comment] 2020-09-23 03:47
i use recording a lot and this my first segmentation fault....

**Comment by pljones** [comment] 2020-09-23 07:49
@corrados, it's hard to say -- as @mawess says, it doesn't appear directly related as recording generally doesn't cause a problem.  Is there any way to get a build that generates more diagnostics?  (e.g. a stack trace)

@mawess, how many users do you generally get on the server?  Can you think of anything that might have been different here?

**Comment by mawess** [comment] 2020-09-23 10:02
@pljones We are usually 17-20 clients.

**Comment by corrados** [comment] 2020-09-24 14:33
Fortunately, I found an issue which is most probably causing the segmentation fault. The jam recorder is not thread-safe. In https://github.com/corrados/jamulus/blob/master/src/recorder/jamrecorder.cpp#L171 you check by an if-condition that iChID is not chIdDisconnected. But the variable iChID can change its state at any point in the function Frame() because it could be changed by another thread. You have to use a Mutex instead of an if-condition instead to solve the issue. @pljones, can you please fix this issue?

**Comment by corrados** [comment] 2020-09-25 05:02
@sthenos Until we either clarify that there is no issue in the jam recorder or we fix a possible bug, as a precaution you should not enable the recording function on any of your Live Studio Jamulus servers during the Worldjam since the server could crash at any time during a live performance.

**Comment by pljones** [comment] 2020-09-25 16:27
> The jam recorder is not thread-safe. 

Almost certainly not...

> In https://github.com/corrados/jamulus/blob/master/src/recorder/jamrecorder.cpp#L171 you check by an if-condition that iChID is not chIdDisconnected. 

> But the variable iChID can change its state at any point in the function Frame() because it could be changed by another thread. 

How can `iChID` be changed?  It's local to the function, isn't it?  (It's a simple type.)  The only object is the `data` vector.

Or do you mean the references such as `vecptrJamClients[iChID]`?

> You have to use a Mutex instead of an if-condition instead to solve the issue. @pljones, can you please fix this issue?

Why would it replace the if?  I'd have thought I'd need a Mutex around the whole process, making it single-threaded...

**Comment by sthenos** [comment] 2020-09-25 16:30
Ah thanks @corrados for letting me know.  I was planning on enabling recording.

**Comment by corrados** [comment] 2020-09-25 18:52
> Do you mean the references such as vecptrJamClients[iChID]?

Yes, I should have looked a bit close at your code. Ok, now I took some more time analyzing the problem:
- In SetRecordingDir you create a thread for the jam recorder with moveToThread(), therefore all QObject::connect from outside this thread are queued and no direct calls (as is with connection inside the same thread per default)
- The CChannel emits Disconnected if a client is disconnected -> this arrives in DisconnectClient() at any time (since it is a different thread) and does `delete vecptrJamClients[iChID];`
- The CServer emits AudioFrame which arrives at any time in CJamSession::Frame and works on vecptrJamClients[iChID].
-> Not thread safe

You need to introduce a Mutex inside the CJamSession class which secures all access on shared resources like the vecptrJamClients.

> > The jam recorder is not thread-safe.
> Almost certainly not...

I hope I could convince you. If not, I will try and try and try again ;-).

**Comment by pljones** [comment] 2020-09-26 07:57
OK, thanks - I think I've got the idea.

I didn't even try when writing it as I didn't want to introduce bits I didn't have any idea about (i.e. the Mutexes) whilst also trying to get the threading working.  I was sort of vaguely aware it was probably not thread-safe...

**Comment by pljones** [comment] 2020-09-26 12:22
I've put the mutex in the CJamRecorder, as that's what handles the signals.

**Comment by corrados** [comment] 2020-09-26 15:57
As I have merged you code, do you think we should close this one? Or should we wait for you to test the new code with your server first?

**Comment by pljones** [comment] 2020-09-26 16:17
@mawess Do you want to try testing the git version, too?

I'm running it on the jamulus.drealm.info in the All Genres server list.

I've not been getting much traffic - I don't think it's _likely_ to happen with only one connection active.  Far more likely with multiple connections, I'd have thought.  I guess it's only since r3_5_11, with increased multi-threading of the connection processing and hence increased AudioFrame concurrency, that the likelihood of this happening has risen significantly.  I've not seen the problem with r3_5_11 here (and I run with -T), though, so even if I don't see a problem with the amended code, it's not really going to prove much.

**Comment by mawess** [comment] 2020-09-26 16:35
hm. I'm running this on mac so I need a mac installer...

**Comment by pljones** [comment] 2020-09-27 08:33
I've asked on Facebook for people to drop by my server in groups to see how it works.  Hopefully we'll get some replies.

**Comment by corrados** [comment] 2020-09-28 18:31
As we most probably have solved the issue by inserting a Mutex, I close this Issue now. If the problem occurs again, please re-open this Issue or create a new one.

**Closed by corrados** 2020-09-28 18:31 UTC
Labels: bug, development in progress
