### ISSUE TITLE
[Feature Request] Way to Stream Individual Audio Streams from Jamulus Server Near-live with Jack

### ISSUE THREAD

**Issue by brandflake11** [corrados/jamulus#174] opened 2020-05-05 13:28 UTC
Would it be possible to get the individual streams as they come into the server into Jack? Say, you have a Jamulus server running, and 3 people connect. How hard would it be to get the three people's audio as soon as they come in into Jack to then be live processed by another program? I would really like to have this option/feature when running a Jamulus server, to then live spatialize the independent audio streams into a multichannel speaker setup.

If this feature is impossible, would it be possible to grab the audio streams as they are being recorded from the Jamulus server to then do this?

Thanks for your support!

**Comment by elliotclee** [comment] 2020-05-05 20:52
This is a dupe of #146 . I would love to have this, and I still think it is doable, but I don't have time to devote to writing the code, and the people who do write code choose to do other stuff.

**Comment by corrados** [comment] 2020-05-07 19:44
I agree that this is a duplicate. Therefore I will close this issue now. If the originator of this Issue does not agree with this, then please just re-open the Issue.

**Closed by corrados** 2020-05-07 19:44 UTC
Labels: duplicate, feature request
