### ISSUE TITLE
Grouping faders in the client

### ISSUE THREAD

**Issue by enorson** [corrados/jamulus#202] opened 2020-05-11 09:38 UTC
When jamming with big ensembles (we had an entire 20 piece big band in a jam yesterday) it would be very valuable to be able to group faders, to have them move in "proportional sync". That way, mixing "on the fly" would be a lot easier with big ensembles - one could pre mix section per section in the band, and then use the groups to set the balance of the band. Even 4 fader groups would be plenty enough.

**Comment by corrados** [comment] 2020-05-12 15:03
This is more or less a duplicate of #178. Both issues want to modify the order of the faders. If you agree I would like to mention your Issue in the #178 and close this one.

**Comment by enorson** [comment] 2020-05-12 15:49
Sure! Although to me, moving the faders isn't as important as making fader
groups. But yes, moving them would be nice as well!

/Magnus

Den tis 12 maj 2020 17:04Volker Fischer <notifications@github.com> skrev:

**Comment by enorson** [comment] 2020-05-12 15:52
To clarify: im not concerned with the order of the faders as such. I just
want to be able to make groups like on a digital mixer, so that you can
pull on one of the faders and have the rest of the group move in unison.

Den tis 12 maj 2020 17:04Volker Fischer <notifications@github.com> skrev:

**Comment by corrados** [comment] 2020-05-12 15:58
Oh, I see. Then this is something different than in #178. So let's keep this one open then.

**Comment by corrados** [comment] 2020-06-20 19:17
@enorson "_Even 4 fader groups would be plenty enough_": We have just implemented a grouping feature: https://github.com/corrados/jamulus/pull/379. It looks like this:
![grafik](https://user-images.githubusercontent.com/46655886/85209820-37de9d80-b33b-11ea-8755-e50a80093da3.png)
If you switch on the grp for the faders, they are moved in sync. I know this is not the "4 fader groups" which you requested but I think this will help you. Do you think this implementation will be enough for you or do you really need the 4 fader groups to be productive?

**Comment by iainhallam** [comment] 2020-06-20 19:38
That's a step forward but for mixing sections, multiple groups would really be needed, otherwise the person mixing will spend the whole session clicking Grp checkboxes to move them together, then clicking them again to change to another group selection for the next section of players. For me, the ideal would be to manually add faders for groups, then have a matrix view or drop down on the player faders that selects which group they go in. Have these group faders at the start of the list, and it would be very quick to adjust the mix of sections.

**Comment by enorson** [comment] 2020-06-20 19:53
It's certainly a very welcome thing and a big improvement, but more groups
would be even better! I play in the Swedish Jamulus big band, and what
would be ideal for the big band setting would be to have one group for the
sax section, one for trombones, one for trumpets and one for the rhythm
section - for a total of four. The purpose of course being to get a better
chance to keep up with the mic while rehearsing .. it's impossible to find
time to manipulate 20 faders while playing, but one group per section is a
whole different matter.

Thank you for taking the time, and thanks for listening to all the
suggestions you're getting - this is true top class!

/Magnus

Den lör 20 juni 2020 21:17Volker Fischer <notifications@github.com> skrev:

**Comment by WolfganP** [comment] 2020-06-20 19:55
Can't the fader items be made selectable via standard Control-Shift-click gestures and that way have dynamic group controls? 
Paired with the recent fader name-ordering changes, it may be a very flexible solution...

**Comment by enorson** [comment] 2020-06-20 19:56
Just a drop down menu instead of the checkbox would get the job done for
me.. like a drop down menu where you could either leave a fader unselected,
or select a group number (1,2,3 or 4)

/Magnus

Den lör 20 juni 2020 21:38Iain Hallam <notifications@github.com> skrev:

**Comment by enorson** [comment] 2020-06-28 12:25
Hi again!

Just tried out the fader grouping in the newly released 3.5.7.
Unfortunately there's a problem with the way the faders move in relation to
each other.

Normally, grouped faders move whilst keeping the proportional relationship
between them. So, let's say one fader is at max (1) and the other at 0.5,
and then you group them. Now, when you move the louder fader down to 0.5,
the other fader should end up at 0.25 thus keeping the mix sounding the
same.

In this version, however, an ABSOLUTE relationship is preserved. So, when
performing the experiment above, lowering the louder fader to 1 makes the
softer one "hit the floor" at zero. Keep on lowering the louder one and the
mix changes so that the next time you pull the fader up again, the mix is
changed.

This, unfortunately, renders the grouping dysfunctional in this
implementation.

Other than that - nice update! I love the "sort by instrument" feature!

/Magnus

Den lör 20 juni 2020 kl 21:17 skrev Volker Fischer <notifications@github.com

**Comment by corrados** [comment] 2020-06-28 12:43
> Now, when you move the louder fader down to 0.5, the other fader should end up at 0.25 thus keeping the mix sounding the same.

This, I do not understand. The unit of the faders is dB (sind version 3.5.0). If you lower the volume of one fader in the group by, let's say, 3 dB, all the other faders are also lowered by 3 dB. What would that be in your proposed implementation? If you lower one fader by 3 dB, do you want the others to be lowered by 1.5 dB?

**Comment by enorson** [comment] 2020-06-29 07:40
Found it difficult to put into words how I mean, so I made a little video
clip. Hope this makes sense to you!

/Magnus

https://youtu.be/7oA4bHKCiF0

Den sön 28 juni 2020 kl 14:43 skrev Volker Fischer <notifications@github.com

**Comment by corrados** [comment] 2020-06-29 14:47
Thanks for your video. This makes now sense to me. Do you know if this behavior is common to all (or most of) the DAWs? Or is it just a special case for the DAW you are using?

**Comment by corrados** [comment] 2020-06-29 14:55
I just found the following video: https://youtu.be/5w81K1XKO8o
It is interesting. If you look on how the faders move in that example, it seems if the faders are above half the range, they are moving like they do right now in Jamulus. Just if they are below a certain threshold, they seem to move proportional as in your video. What do you think about this behavior?

**Comment by enorson** [comment] 2020-06-29 15:48
All DAWS I've used (Cubase, Studio One, Protools), and all digital mixing
consoles I've used, they all behave in this way.

Regarding your clip: As far as I can tell they do move like I showed you,
it's just that the closer they are to each other's value, the less
pronounced the difference appears on screen.

Also, it might be a question of the tapering of the faders themselves...
sometimes they have different "gearing" at different points of their
travel. But the grouping principle remains the same though - when you hit
the "group" switch, a mathematical relationship is established between the
faders. Let's say (for the sake of simplicity) that fader #2 gets a
mathematical coefficient with regards to fader #1; which it maintains as
you move the faders. This coefficient has to do with perceived sound
pressure level; so ideally - if we take the principle I showed in my clip -
if fader #1 is set to "1" and fader #2 is set to "0.5", then sound source
#2 should indeed be perceived as "half as loud". And no matter what you do
with fader #1 ... you might lower it to "0,6" for instance ... but #2
should then still be perceived as "half as loud" (so, therefore it should
move to "0.3".

Den mån 29 juni 2020 kl 16:47 skrev Volker Fischer <notifications@github.com

**Comment by enorson** [comment] 2020-06-29 16:05
Check out this from Cubase (scroll to 3:00):
https://www.youtube.com/watch?v=fyKqmmbxTgA

Or here for Logic: (scroll to 7:45):
https://www.youtube.com/watch?v=JRe68qPVnPU

/Magnus

Den mån 29 juni 2020 kl 16:55 skrev Volker Fischer <notifications@github.com

**Comment by corrados** [comment] 2020-06-29 17:02
Ok, I am convinced ;-). I'll try to change this for the next Jamulus release version.

**Comment by corrados** [comment] 2020-06-30 17:45
I did some test implementation:
![AdG4M1ywJs](https://user-images.githubusercontent.com/46655886/86158987-ed62db00-bb09-11ea-96e6-20631442994c.gif)
As you can see, now the faders move proportionally. I hope this is what you want.
At the end of the short video you can see that I move the fader to the top so that the others clip. When I then move it down, the faders have a new relationship after the clipping. Is this what you would expect?

**Comment by enorson** [comment] 2020-07-01 06:48
Looks great!

No, that's not expected behaviour. Normally, in DAWs, the original
relationship between faders is remembered even if a few faders max out
temporarily, so when you take them back down after maxing them out they
revert back to the stored relationship.

Now, if the "grp" switch was replaced with a drop down menu with 5
choices... Say " *blank*, A, B, C, D " so that each fader could be either
ungrouped (in the blank position) or assigned to one of four groups A B C
or D... Then heaven would open up and ask my dreams come true. Well that's
slightly exaggerated, but you understand... ;)

Excellent work! Thank you so much for your efforts, it's amazing.

/Magnus

Den tis 30 juni 2020 19:45Volker Fischer <notifications@github.com> skrev:

**Comment by corrados** [comment] 2020-07-01 13:14
Ok, next try:
![L3IksyTfpl](https://user-images.githubusercontent.com/46655886/86247887-69fac580-bbad-11ea-8b6a-901c685a9a34.gif)
Now it should be as expected, right?

**Comment by corrados** [comment] 2020-07-01 13:19
One open question remains. If one fader max out and you move that fader, it right now jumps the other fader to a position where the original ratio is maintained. It this the expected behaviour? Please see the following video:
![tcTaHm1lC0](https://user-images.githubusercontent.com/46655886/86248428-2eacc680-bbae-11ea-9edb-028edcd26f5e.gif)

**Comment by enorson** [comment] 2020-07-01 15:44
This is a very good question - one that I've never thought about. So I did
some comparative research and there doesn't seem to be consensus among the
DAWs about this.

In Studio One: Pulling back down on the SAME fader keeps the relationship,
but if I change and pull down a different fader - the relationship is
changed. I don't like this.

Pro Tools: Whenever something "hits the ceiling", it changes the
relationship at once. I don't like that either.

Cubase and Ardour: These DAWs have what I, after having thought about the
matter long and hard, consider to be the best solution to the problem.
After all, the whole point of making a fader group at all is to preserve a
mix. So what do they do? They make the loudest fader a "limiting factor"
for the movement of the whole group. So, whenever a fader hits the ceiling,
no faders are allowed to move to louder positions. The loudest fader marks
the "end of travel" for the whole group. This is, I think, the best way!!
Because, like I said, the whole point is to keep the mix sounding the same
and this is the only variant that truly does just that.

/Magnus

Den ons 1 juli 2020 kl 15:19 skrev Volker Fischer <notifications@github.com

**Comment by enorson** [comment] 2020-07-01 15:49
But come to think of it - your current variant (with the "pop back") is
actually a very good way too. This way, you CAN push the group louder,
temporarily sacrificing the mix to gain volume... but you don't actually
lose the mix, it is instantly brought back by pulling on a maxed out fader.
I like this one just as much as the Cubase/Ardour variant!

Den ons 1 juli 2020 kl 17:44 skrev Magnus Enorson <magnusenorson@gmail.com>:

**Comment by corrados** [comment] 2020-07-01 16:57
Thanks for your research.

> They make the loudest fader a "limiting factor" for the movement of the whole group.

That will be pretty hard to implement in Jamulus.

> your current variant (with the "pop back") is actually a very good way too. [...] I like this one just as much as the Cubase/Ardour variant!

Puh, I am lucky that you like that. That saves me a lot of work ;-). But I agree with you. I think the way it is implemented right now is a good solution.

Are you able to compile Jamulus to test the new code?

**Comment by corrados** [comment] 2020-07-03 14:04
One more question: In the DAWs you mentioned: If you group some channels, the faders are synchronized. Are other settings, like the Pan, are also synchronized? I.e. if you group two channels and change the Pan of one channel, is the other channel Pan also changed?

**Comment by enorson** [comment] 2020-07-03 14:47
Normally in DAWs you can select what's to be included in a group. The fader
is always synced, and then you can also optionally select things like Pan,
Mutes, Solos, Aux outs etc.

/Magnus

Den fre 3 juli 2020 kl 16:05 skrev Volker Fischer <notifications@github.com

**Comment by iainhallam** [comment] 2020-07-03 16:01
This might be easier in UI if each group created a new fader at the beginning of the channel list - the original settings and mix can be maintained on the individual channels, while the group can also have its level and panning adjusted together.

**Comment by corrados** [comment] 2020-07-04 07:26
How do you like this:
![nJ1BdTmae0](https://user-images.githubusercontent.com/46655886/86507417-53848200-bdd8-11ea-8bd2-ef6db96a4cda.gif)
Still a lot to do but things seem to converge...

**Comment by corrados** [comment] 2020-07-04 10:05
This could be a possible workflow when having a large group of musicians:
![r49xQBhdCB](https://user-images.githubusercontent.com/46655886/86510242-55f1d680-bdee-11ea-94ca-b4ee562787dd.gif)
Still work in progress...

**Comment by enorson** [comment] 2020-07-04 11:33
That looks totally awesome! Great work!

/Magnus

Den lör 4 juli 2020 09:27Volker Fischer <notifications@github.com> skrev:

**Comment by WolfganP** [comment] 2020-07-04 14:00
Excellent! Great work @corrados 
Is there any way you can pair the groups membership with a subtle change of the fader's column background? (ir Grp1 has a light green background hue, Grp2 light blue, Grp3 light yellow, ...) for even easier visual identification of the active groups?

**Comment by corrados** [comment] 2020-07-04 17:04
As you can see in my short video, I already implemented some color coding. Let's start with that. Later on we could eventually add more color coding. But most Jamulus users will not have the need for using groups at all. Only if you have choirs or e.g. big bands they will need it.

**Comment by corrados** [comment] 2020-07-05 15:06
Ok, the code is ready in the Git repo. I'll close this issue now. If the release is out and you find issues with the new functionality, please open a new bug report issue.

**Closed by corrados** 2020-07-05 15:06 UTC
Labels: development in progress, feature request
